-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Clubs - CSL
-- Generated: 2026-01-31T21:47:34.267Z
-- Total Records: 67
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (1, 'Central Park Rangers Red', 1, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (2, 'NY Athletic Club', 2, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (3, 'Richmond County FC', 3, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (4, 'FC Sandzak', 4, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (5, 'Borgetto FC', 5, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (6, 'NY Shamrocks', 6, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (7, 'Manhattan Kickers', 7, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (8, 'Kelmendi FC NY', 8, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (9, 'Polonia SC', 9, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (10, 'Zum Schneider FC 03', 10, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (11, 'Missile FC', 11, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (12, 'NY Ukrainians', 12, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (13, 'NYPD FC', 13, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (14, 'NY International FC', 14, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (15, 'Manhattan Celtic', 15, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (16, 'Block FC', 16, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (17, 'Central Park Rangers United', 17, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (18, 'Hoboken FC 1912', 18, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (19, 'Brooklyn City FC', 19, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (20, 'Stal Mielec NY', 20, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (21, 'FC Japan', 21, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (22, 'Williamsburg International FC', 22, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (23, 'Yemen United SC', 23, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (24, 'Manhattan FC', 24, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (25, 'Desportiva Sociedad', 25, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (26, 'KidSuper Samba AC', 26, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (27, 'SC Gjoa Yellow Hook', 27, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (28, 'SC Eintracht', 28, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (29, 'CD Iberia', 29, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (30, 'Central Park Rangers Green', 30, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (31, 'Falco FC', 31, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (32, 'Central Park Rangers Young Boys', 32, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (33, 'NY Pancyprian Freedoms', 33, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (34, 'NY Albanians FC', 34, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (35, 'Laberia FC', 35, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (36, 'Afghan Ittihad FC', 36, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (37, 'Barnstonworth Rovers FC', 37, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (38, 'Panatha USA', 38, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (39, 'Aurora FC', 39, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (40, 'Vera FC', 40, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (41, 'Lansdowne Yonkers FC Metro', 41, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (42, 'NY Legacy FC', 42, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (43, 'Guyana Sunnydale Veterans FC', 43, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (44, 'NY Galicia', 44, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (45, 'NYC AlphaStars Club', 45, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (46, 'Tibet FC', 46, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (47, 'Vibes FC', 47, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (48, 'Central Park Rangers 1999', 48, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (49, 'Desportiva Sociedad City', 49, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (50, 'NY Croatia', 50, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (51, 'FC Partizani NY', 51, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (52, 'Desportiva Sociedad Fury', 52, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (53, 'Caribbean FCA', 53, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (54, 'Riverside Squires', 54, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (55, 'Astoria Knights', 55, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (56, 'Bajas FC', 56, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (57, 'Clarkstown SC', 57, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (58, 'Soccer Legion FC Men', 58, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (59, 'NYPD FC Veterans', 59, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (60, 'Ridgewood Romac SC', 60, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (61, 'Central Park Rangers', 61, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (62, 'SC Gjoa Over-40', 62, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (63, 'Cozmoz FC', 63, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (64, 'Barnstonworth Rovers', 64, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (65, 'Doxa SC', 65, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (66, 'Central Park Rangers Orange', 66, 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id, source_system_id) VALUES (67, 'NY Irish SC', 67, 3) ON CONFLICT (id) DO NOTHING;
