-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Teams - CSL (Curated)
-- Teams linked to existing APSL clubs where matched. Total: 101
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Central Park Rangers Red', '6783', 121, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'NY Athletic Club', '6817', 124, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Richmond County FC', '6843', 120, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'FC Sandzak', '6797', 10003, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Borgetto FC', '6768', 10004, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'NY Shamrocks', '6828', 10005, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Manhattan Kickers', '6811', 10006, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Kelmendi FC NY', '6802', 10007, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Polonia SC', '6841', 10008, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Zum Schneider FC 03 II', '6858', 123, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Missile FC', '6814', 10010, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Central Park Rangers Red II', '6784', 121, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Polonia SC II', '6842', 10008, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Borgetto FC II', '6770', 10004, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Manhattan Kickers II', '6813', 10006, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'NY Shamrocks II', '6831', 10005, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'NY Athletic Club II', '6818', 124, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'FC Sandzak II', '6798', 10003, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Richmond County FC II', '6844', 120, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Zum Schneider FC 03 III', '6859', 123, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Kelmendi FC NY II', '6803', 10007, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Missile FC II', '6815', 10010, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'NY Ukrainians', '6832', 10011, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'NYPD FC', '6836', 10012, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'NY International FC', '6822', 119, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Manhattan Celtic II', '6808', 10014, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Block FC', '6766', 10015, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Central Park Rangers United', '6779', 121, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Hoboken FC 1912 II', '6800', 115, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Brooklyn City FC', '6772', 10017, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Stal Mielec NY', '6850', 10018, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'FC Japan', '6794', 10019, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Williamsburg International FC', '6854', 10020, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Yemen United SC', '6857', 10021, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Manhattan FC', '6908', 10022, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Desportiva Sociedad', '6788', 10023, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'KidSuper Samba AC II', '6804', 10024, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'SC Gjoa Yellow Hook', '6852', 10025, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'SC Eintracht', '6846', 10026, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'CD Iberia', '6774', 10027, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Central Park Rangers United II', '6781', 121, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'NY Ukrainians II', '6834', 10011, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Hoboken FC 1912 III', '6801', 115, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Yemen United SC II', '7213', 10021, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'NYPD FC II', '6837', 10012, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'NY International FC II', '6823', 119, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Manhattan Celtic III', '6809', 10014, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Desportiva Sociedad II', '6791', 10023, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'KidSuper Samba AC III', '7584', 10024, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'CD Iberia II', '7678', 10027, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Brooklyn City FC II', '6773', 10017, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'SC Eintracht II', '6848', 10026, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Manhattan FC II', '7212', 10022, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'SC Gjoa Yellow Hook II', '7211', 10025, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Block FC II', '6767', 10015, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Williamsburg International FC II', '6856', 10020, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'FC Japan II', '6795', 10019, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Stal Mielec NY II', '6851', 10018, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Central Park Rangers Green', '6776', 121, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Falco FC', '6793', 100, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Central Park Rangers Young Boys', '6785', 121, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'NY Pancyprian Freedoms II', '6826', 116, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'NY Albanians FC', '6816', 10030, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Laberia FC', '6805', 10031, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Afghan Ittihad FC', '6759', 10032, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Barnstonworth Rovers FC', '6762', 10033, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Panatha USA', '6840', 10034, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Aurora FC', '6761', 10035, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Vera FC', '7717', 10036, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Lansdowne Yonkers FC Metro', '6807', 114, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'NY Legacy FC', '6909', 10038, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Guyana Sunnydale Veterans FC', '7885', 10039, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'NY Galicia', '6820', 10040, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'NYC AlphaStars Club', '6835', 10041, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Tibet FC', '6853', 10042, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Vibes FC', '7598', 10043, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Central Park Rangers 1999', '6775', 121, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Williamsburg International FC III', '6855', 10020, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Desportiva Sociedad City', '6789', 10023, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'NY Croatia', '6819', 10044, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'FC Partizani NY', '6796', 10045, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Desportiva Sociedad Fury', '6790', 10023, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Caribbean FCA', '12292', 112, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Riverside Squires', '10041', 10047, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Astoria Knights II', '11550', 10048, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Bajas FC', '9849', 10049, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Clarkstown SC', '12632', 10050, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Soccer Legion FC Men', '8335', 10051, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'NYPD FC Veterans', '6838', 10012, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Ridgewood Romac SC', '6845', 10052, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Manhattan Kickers Legends', '6812', 10006, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Manhattan Celtic Masters', '6810', 10014, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Central Park Rangers Legends', '6780', 121, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'SC Gjoa Over-40', '6849', 10025, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Cozmoz FC', '6787', 10053, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'SC Eintracht Legends', '6847', 10026, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Barnstonworth Rovers Old Boys', '6763', 10033, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Doxa SC Legends', '7883', 118, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'Central Park Rangers Orange', '6782', 121, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'NY Shamrocks Legends', '6829', 10005, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (null, 'NY Irish SC Legends', '6825', 10055, 3) ON CONFLICT (source_system_id, external_id) DO NOTHING;
