-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Teams - CSL
-- Generated: 2026-01-31T21:47:34.267Z
-- Total Records: 101
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (1, 'Central Park Rangers Red', '6783', 1, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (2, 'NY Athletic Club', '6817', 2, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (3, 'Richmond County FC', '6843', 3, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (4, 'FC Sandzak', '6797', 4, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (5, 'Borgetto FC', '6768', 5, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (6, 'NY Shamrocks', '6828', 6, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (7, 'Manhattan Kickers', '6811', 7, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (8, 'Kelmendi FC NY', '6802', 8, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (9, 'Polonia SC', '6841', 9, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (10, 'Zum Schneider FC 03 II', '6858', 10, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (11, 'Missile FC', '6814', 11, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (12, 'Central Park Rangers Red II', '6784', 1, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (13, 'Polonia SC II', '6842', 9, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (14, 'Borgetto FC II', '6770', 5, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (15, 'Manhattan Kickers II', '6813', 7, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (16, 'NY Shamrocks II', '6831', 6, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (17, 'NY Athletic Club II', '6818', 2, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (18, 'FC Sandzak II', '6798', 4, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (19, 'Richmond County FC II', '6844', 3, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (20, 'Zum Schneider FC 03 III', '6859', 10, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (21, 'Kelmendi FC NY II', '6803', 8, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (22, 'Missile FC II', '6815', 11, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (23, 'NY Ukrainians', '6832', 12, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (24, 'NYPD FC', '6836', 13, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (25, 'NY International FC', '6822', 14, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (26, 'Manhattan Celtic II', '6808', 15, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (27, 'Block FC', '6766', 16, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (28, 'Central Park Rangers United', '6779', 17, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (29, 'Hoboken FC 1912 II', '6800', 18, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (30, 'Brooklyn City FC', '6772', 19, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (31, 'Stal Mielec NY', '6850', 20, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (32, 'FC Japan', '6794', 21, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (33, 'Williamsburg International FC', '6854', 22, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (34, 'Yemen United SC', '6857', 23, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (35, 'Manhattan FC', '6908', 24, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (36, 'Desportiva Sociedad', '6788', 25, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (37, 'KidSuper Samba AC II', '6804', 26, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (38, 'SC Gjoa Yellow Hook', '6852', 27, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (39, 'SC Eintracht', '6846', 28, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (40, 'CD Iberia', '6774', 29, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (41, 'Central Park Rangers United II', '6781', 17, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (42, 'NY Ukrainians II', '6834', 12, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (43, 'Hoboken FC 1912 III', '6801', 18, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (44, 'Yemen United SC II', '7213', 23, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (45, 'NYPD FC II', '6837', 13, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (46, 'NY International FC II', '6823', 14, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (47, 'Manhattan Celtic III', '6809', 15, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (48, 'Desportiva Sociedad II', '6791', 25, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (49, 'KidSuper Samba AC III', '7584', 26, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (50, 'CD Iberia II', '7678', 29, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (51, 'Brooklyn City FC II', '6773', 19, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (52, 'SC Eintracht II', '6848', 28, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (53, 'Manhattan FC II', '7212', 24, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (54, 'SC Gjoa Yellow Hook II', '7211', 27, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (55, 'Block FC II', '6767', 16, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (56, 'Williamsburg International FC II', '6856', 22, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (57, 'FC Japan II', '6795', 21, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (58, 'Stal Mielec NY II', '6851', 20, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (59, 'Central Park Rangers Green', '6776', 30, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (60, 'Falco FC', '6793', 31, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (61, 'Central Park Rangers Young Boys', '6785', 32, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (62, 'NY Pancyprian Freedoms II', '6826', 33, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (63, 'NY Albanians FC', '6816', 34, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (64, 'Laberia FC', '6805', 35, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (65, 'Afghan Ittihad FC', '6759', 36, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (66, 'Barnstonworth Rovers FC', '6762', 37, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (67, 'Panatha USA', '6840', 38, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (68, 'Aurora FC', '6761', 39, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (69, 'Vera FC', '7717', 40, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (70, 'Lansdowne Yonkers FC Metro', '6807', 41, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (71, 'NY Legacy FC', '6909', 42, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (72, 'Guyana Sunnydale Veterans FC', '7885', 43, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (73, 'NY Galicia', '6820', 44, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (74, 'NYC AlphaStars Club', '6835', 45, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (75, 'Tibet FC', '6853', 46, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (76, 'Vibes FC', '7598', 47, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (77, 'Central Park Rangers 1999', '6775', 48, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (78, 'Williamsburg International FC III', '6855', 22, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (79, 'Desportiva Sociedad City', '6789', 49, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (80, 'NY Croatia', '6819', 50, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (81, 'FC Partizani NY', '6796', 51, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (82, 'Desportiva Sociedad Fury', '6790', 52, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (83, 'Caribbean FCA', '12292', 53, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (84, 'Riverside Squires', '10041', 54, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (85, 'Astoria Knights II', '11550', 55, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (86, 'Bajas FC', '9849', 56, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (87, 'Clarkstown SC', '12632', 57, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (88, 'Soccer Legion FC Men', '8335', 58, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (89, 'NYPD FC Veterans', '6838', 59, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (90, 'Ridgewood Romac SC', '6845', 60, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (91, 'Manhattan Kickers Legends', '6812', 7, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (92, 'Manhattan Celtic Masters', '6810', 15, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (93, 'Central Park Rangers Legends', '6780', 61, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (94, 'SC Gjoa Over-40', '6849', 62, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (95, 'Cozmoz FC', '6787', 63, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (96, 'SC Eintracht Legends', '6847', 28, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (97, 'Barnstonworth Rovers Old Boys', '6763', 64, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (98, 'Doxa SC Legends', '7883', 65, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (99, 'Central Park Rangers Orange', '6782', 66, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (100, 'NY Shamrocks Legends', '6829', 6, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
INSERT INTO scraped_teams (id, name, external_id, club_id, source_system_id) VALUES (101, 'NY Irish SC Legends', '6825', 67, 3) ON CONFLICT (external_id, source_system_id) DO NOTHING;
