# Aider configuration for Football Home
model: claude-sonnet-4-20250514
dark-mode: true
no-auto-commits: true
pretty: true
stream: true

# Context files (always included)
read:
  - README.md
  - .github/copilot-instructions.md

# Ignore patterns (use aiderignore file instead)
# See: https://aider.chat/docs/config/aider_ignore.html
