-- ========================================
-- APSL COACHES
-- ========================================
-- Scraped from APSL roster pages (top of page)
-- Generated by ApslScraper.js
-- ========================================

-- This file will be auto-generated by the scraper
-- Coaches extend the users table with coaching-specific fields

