-- ========================================
-- CASA COACHES
-- ========================================
-- Scraped from CASA roster data
-- Generated by CasaScraper.js
-- ========================================

-- This file will be auto-generated by the scraper
-- Coaches extend the users table with coaching-specific fields

