-- ========================================
-- APSL TEAM COACHES
-- ========================================
-- Scraped from APSL roster pages
-- Generated by ApslScraper.js
-- ========================================

-- This file will be auto-generated by the scraper
-- Links coaches to teams with their role

