-- ========================================
-- PLAYER PARENTS
-- ========================================
-- Junction table linking players to their parents
-- Step 3: Associate parents with their children
-- ========================================

-- No player-parent associations configured yet
--
-- USAGE:
-- INSERT INTO player_parents (player_id, parent_id, relationship_type, is_primary_contact, is_emergency_contact)
-- VALUES 
--   ('player-id', 'parent-id', 'Father', true, true),
--   ('player-id', 'parent-id-2', 'Mother', true, true);
