-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Organizations - APSL
-- Total Records: 186
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO organizations (id, name) VALUES (100, 'Falcons FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (101, 'Scrub Nation') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (102, 'Praia Kapital') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (103, 'South Coast Union') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (104, 'Project Football') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (105, 'Invictus FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (106, 'Fitchburg FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (107, 'Somerville United FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (108, 'KO Elites') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (109, 'Glastonbury Celtic') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (110, 'Wildcat FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (111, 'Hermandad Connecticut') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (112, 'Caribbean FCA') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (113, 'NY Greek Americans') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (114, 'Lansdowne Yonkers FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (115, 'Hoboken FC 1912') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (116, 'NY Pancyprian Freedoms') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (117, 'Leros SC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (118, 'Doxa FCW') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (119, 'NY International FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (120, 'Richmond County FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (121, 'Central Park Rangers FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (122, 'SC Vistula Garfield') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (123, 'Zum Schneider FC 03') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (124, 'NY Athletic Club') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (125, 'WC Predators') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (126, 'Alloy Soccer Club') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (127, 'Oaklyn United FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (128, 'Real Central NJ Soccer') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (129, 'Philadelphia Heritage SC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (130, 'Vidas United FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (131, 'Philadelphia Soccer Club') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (132, 'Jersey Shore Boca') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (133, 'GAK') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (134, 'Lighthouse 1893 SC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (135, 'Sewell Old Boys FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (136, 'Medford Strikers') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (137, 'Nova FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (138, 'VA Marauders FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (139, 'Wave FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (140, 'PFA EPSL') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (141, 'Grove Soccer') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (142, 'Christos FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (143, 'Delmarva Thunder') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (144, 'PW Nova') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (145, 'Germantown City FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (146, 'Terminus FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (147, 'Prima FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (148, 'Majestic SC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (149, 'Peachtree FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (150, 'Bel Calcio FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (151, 'Buckhead SC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (152, 'Alliance SC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (153, 'Georgia United FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (154, 'SC Gwinnett') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (155, 'AC Arlington FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (156, 'Foro SC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (157, 'North Texas Prowl FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (158, 'Texas Rage FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (159, 'Team 10370') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (160, 'Team 10399') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (161, 'Team 10742') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (162, 'Team 137416') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (163, 'Team 13836') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (164, 'Team 16078') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (165, 'Team 19885') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (166, 'Team 35025') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (167, 'Team 35383') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (168, 'Team 35791') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (169, 'Team 35792') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (170, 'Team 35793') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (171, 'Team 35794') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (172, 'Team 35795') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (173, 'Team 35796') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (174, 'Team 35797') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (175, 'Team 35798') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (176, 'Team 36302') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (177, 'Team 36303') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (178, 'Team 36304') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (179, 'Team 36305') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (180, 'Team 36306') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (181, 'Team 36307') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (182, 'Team 36308') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (183, 'Team 36343') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (184, 'Team 36344') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (185, 'Team 36501') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (186, 'Team 36556') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (187, 'Team 36616') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (188, 'Team 36617') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (189, 'Team 36619') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (190, 'Team 36620') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (191, 'Team 36621') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (192, 'Team 36623') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (193, 'Team 36661') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (194, 'Team 37026') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (195, 'Team 39836') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (196, 'Team 39837') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (197, 'Team 39838') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (198, 'Team 39839') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (199, 'Team 39895') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (200, 'Team 41209') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (201, 'Team 47840') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (202, 'Team 49064') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (203, 'Team 49065') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (204, 'Team 49382') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (205, 'Team 49461') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (206, 'Team 50543') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (207, 'Team 53144') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (208, 'Team 62577') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (209, 'Team 72396') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (210, 'Team 72413') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (211, 'Team 72419') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (212, 'Team 72433') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (213, 'Team 72435') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (214, 'Team 72436') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (215, 'Team 72437') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (216, 'Team 72438') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (217, 'Team 72439') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (218, 'Team 72447') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (219, 'Team 72449') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (220, 'Team 72450') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (221, 'Team 72453') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (222, 'Team 72456') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (223, 'Team 72457') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (224, 'Team 72462') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (225, 'Team 72476') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (226, 'Team 7312') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (227, 'Team 7313') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (228, 'Team 7315') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (229, 'Team 7316') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (230, 'Team 7319') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (231, 'Team 7320') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (232, 'Team 7321') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (233, 'Team 7322') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (234, 'Team 7325') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (235, 'Team 7326') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (236, 'Team 7327') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (237, 'Team 7328') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (238, 'Team 7329') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (239, 'Team 7330') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (240, 'Team 7331') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (241, 'Team 7332') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (242, 'Team 7333') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (243, 'Team 7334') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (244, 'Team 7336') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (245, 'Team 7337') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (246, 'Team 7338') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (247, 'Team 7340') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (248, 'Team 7343') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (249, 'Team 7347') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (250, 'Team 7348') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (251, 'Team 7349') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (252, 'Team 7350') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (253, 'Team 7351') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (254, 'Team 7352') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (255, 'Team 7354') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (256, 'Team 75075') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (257, 'Team 75076') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (258, 'Team 75077') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (259, 'Team 75182') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (260, 'Team 75183') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (261, 'Team 7679') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (262, 'Team 77157') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (263, 'Team 77487') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (264, 'Team 77488') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (265, 'Team 77491') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (266, 'Team 77492') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (267, 'Team 79987') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (268, 'Team 8077') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (269, 'Team 86861') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (270, 'Team 88643') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (271, 'Team 88644') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (272, 'Team 88645') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (273, 'Team 88646') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (274, 'Team 88681') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (275, 'Team 91900') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (276, 'Team 91963') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (277, 'Team 91964') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (278, 'Team 91966') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (279, 'Team 91967') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (280, 'Team 91968') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (281, 'Team 91969') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (282, 'Team 91971') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (283, 'Team 91972') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (284, 'Team 92772') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (285, 'Team 93458') ON CONFLICT (id) DO NOTHING;
