-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Clubs - APSL
-- Total Records: 59
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO clubs (id, name, organization_id) VALUES (100, 'Falcons FC', 100) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (101, 'Scrub Nation', 101) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (102, 'Praia Kapital', 102) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (103, 'South Coast Union', 103) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (104, 'Project Football', 104) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (105, 'Invictus FC', 105) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (106, 'Fitchburg FC', 106) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (107, 'Somerville United FC', 107) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (108, 'KO Elites', 108) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (109, 'Glastonbury Celtic', 109) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (110, 'Wildcat FC', 110) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (111, 'Hermandad Connecticut', 111) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (112, 'Caribbean FCA', 112) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (113, 'NY Greek Americans', 113) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (114, 'Lansdowne Yonkers FC', 114) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (115, 'Hoboken FC 1912', 115) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (116, 'NY Pancyprian Freedoms', 116) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (117, 'Leros SC', 117) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (118, 'Doxa FCW', 118) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (119, 'NY International FC', 119) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (120, 'Richmond County FC', 120) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (121, 'Central Park Rangers FC', 121) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (122, 'SC Vistula Garfield', 122) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (123, 'Zum Schneider FC 03', 123) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (124, 'NY Athletic Club', 124) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (125, 'WC Predators', 125) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (126, 'Alloy Soccer Club', 126) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (127, 'Oaklyn United FC', 127) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (128, 'Real Central NJ Soccer', 128) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (129, 'Philadelphia Heritage SC', 129) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (130, 'Vidas United FC', 130) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (131, 'Philadelphia Soccer Club', 131) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (132, 'Jersey Shore Boca', 132) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (133, 'GAK', 133) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (134, 'Lighthouse 1893 SC', 134) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (135, 'Sewell Old Boys FC', 135) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (136, 'Medford Strikers', 136) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (137, 'Nova FC', 137) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (138, 'VA Marauders FC', 138) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (139, 'Wave FC', 139) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (140, 'PFA EPSL', 140) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (141, 'Grove Soccer', 141) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (142, 'Christos FC', 142) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (143, 'Delmarva Thunder', 143) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (144, 'PW Nova', 144) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (145, 'Germantown City FC', 145) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (146, 'Terminus FC', 146) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (147, 'Prima FC', 147) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (148, 'Majestic SC', 148) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (149, 'Peachtree FC', 149) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (150, 'Bel Calcio FC', 150) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (151, 'Buckhead SC', 151) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (152, 'Alliance SC', 152) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (153, 'Georgia United FC', 153) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (154, 'SC Gwinnett', 154) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (155, 'AC Arlington FC', 155) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (156, 'Foro SC', 156) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (157, 'North Texas Prowl FC', 157) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (158, 'Texas Rage FC', 158) ON CONFLICT (id) DO NOTHING;
