-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Clubs - APSL
-- Total Records: 186
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO clubs (id, name, organization_id) VALUES (100, 'Falcons FC', 100) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (101, 'Scrub Nation', 101) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (102, 'Praia Kapital', 102) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (103, 'South Coast Union', 103) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (104, 'Project Football', 104) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (105, 'Invictus FC', 105) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (106, 'Fitchburg FC', 106) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (107, 'Somerville United FC', 107) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (108, 'KO Elites', 108) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (109, 'Glastonbury Celtic', 109) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (110, 'Wildcat FC', 110) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (111, 'Hermandad Connecticut', 111) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (112, 'Caribbean FCA', 112) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (113, 'NY Greek Americans', 113) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (114, 'Lansdowne Yonkers FC', 114) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (115, 'Hoboken FC 1912', 115) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (116, 'NY Pancyprian Freedoms', 116) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (117, 'Leros SC', 117) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (118, 'Doxa FCW', 118) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (119, 'NY International FC', 119) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (120, 'Richmond County FC', 120) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (121, 'Central Park Rangers FC', 121) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (122, 'SC Vistula Garfield', 122) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (123, 'Zum Schneider FC 03', 123) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (124, 'NY Athletic Club', 124) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (125, 'WC Predators', 125) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (126, 'Alloy Soccer Club', 126) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (127, 'Oaklyn United FC', 127) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (128, 'Real Central NJ Soccer', 128) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (129, 'Philadelphia Heritage SC', 129) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (130, 'Vidas United FC', 130) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (131, 'Philadelphia Soccer Club', 131) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (132, 'Jersey Shore Boca', 132) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (133, 'GAK', 133) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (134, 'Lighthouse 1893 SC', 134) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (135, 'Sewell Old Boys FC', 135) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (136, 'Medford Strikers', 136) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (137, 'Nova FC', 137) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (138, 'VA Marauders FC', 138) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (139, 'Wave FC', 139) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (140, 'PFA EPSL', 140) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (141, 'Grove Soccer', 141) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (142, 'Christos FC', 142) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (143, 'Delmarva Thunder', 143) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (144, 'PW Nova', 144) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (145, 'Germantown City FC', 145) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (146, 'Terminus FC', 146) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (147, 'Prima FC', 147) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (148, 'Majestic SC', 148) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (149, 'Peachtree FC', 149) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (150, 'Bel Calcio FC', 150) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (151, 'Buckhead SC', 151) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (152, 'Alliance SC', 152) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (153, 'Georgia United FC', 153) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (154, 'SC Gwinnett', 154) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (155, 'AC Arlington FC', 155) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (156, 'Foro SC', 156) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (157, 'North Texas Prowl FC', 157) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (158, 'Texas Rage FC', 158) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (159, 'Team 10370', 159) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (160, 'Team 10399', 160) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (161, 'Team 10742', 161) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (162, 'Team 137416', 162) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (163, 'Team 13836', 163) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (164, 'Team 16078', 164) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (165, 'Team 19885', 165) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (166, 'Team 35025', 166) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (167, 'Team 35383', 167) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (168, 'Team 35791', 168) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (169, 'Team 35792', 169) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (170, 'Team 35793', 170) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (171, 'Team 35794', 171) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (172, 'Team 35795', 172) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (173, 'Team 35796', 173) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (174, 'Team 35797', 174) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (175, 'Team 35798', 175) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (176, 'Team 36302', 176) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (177, 'Team 36303', 177) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (178, 'Team 36304', 178) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (179, 'Team 36305', 179) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (180, 'Team 36306', 180) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (181, 'Team 36307', 181) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (182, 'Team 36308', 182) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (183, 'Team 36343', 183) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (184, 'Team 36344', 184) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (185, 'Team 36501', 185) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (186, 'Team 36556', 186) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (187, 'Team 36616', 187) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (188, 'Team 36617', 188) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (189, 'Team 36619', 189) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (190, 'Team 36620', 190) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (191, 'Team 36621', 191) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (192, 'Team 36623', 192) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (193, 'Team 36661', 193) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (194, 'Team 37026', 194) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (195, 'Team 39836', 195) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (196, 'Team 39837', 196) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (197, 'Team 39838', 197) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (198, 'Team 39839', 198) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (199, 'Team 39895', 199) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (200, 'Team 41209', 200) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (201, 'Team 47840', 201) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (202, 'Team 49064', 202) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (203, 'Team 49065', 203) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (204, 'Team 49382', 204) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (205, 'Team 49461', 205) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (206, 'Team 50543', 206) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (207, 'Team 53144', 207) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (208, 'Team 62577', 208) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (209, 'Team 72396', 209) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (210, 'Team 72413', 210) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (211, 'Team 72419', 211) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (212, 'Team 72433', 212) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (213, 'Team 72435', 213) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (214, 'Team 72436', 214) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (215, 'Team 72437', 215) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (216, 'Team 72438', 216) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (217, 'Team 72439', 217) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (218, 'Team 72447', 218) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (219, 'Team 72449', 219) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (220, 'Team 72450', 220) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (221, 'Team 72453', 221) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (222, 'Team 72456', 222) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (223, 'Team 72457', 223) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (224, 'Team 72462', 224) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (225, 'Team 72476', 225) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (226, 'Team 7312', 226) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (227, 'Team 7313', 227) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (228, 'Team 7315', 228) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (229, 'Team 7316', 229) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (230, 'Team 7319', 230) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (231, 'Team 7320', 231) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (232, 'Team 7321', 232) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (233, 'Team 7322', 233) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (234, 'Team 7325', 234) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (235, 'Team 7326', 235) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (236, 'Team 7327', 236) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (237, 'Team 7328', 237) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (238, 'Team 7329', 238) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (239, 'Team 7330', 239) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (240, 'Team 7331', 240) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (241, 'Team 7332', 241) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (242, 'Team 7333', 242) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (243, 'Team 7334', 243) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (244, 'Team 7336', 244) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (245, 'Team 7337', 245) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (246, 'Team 7338', 246) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (247, 'Team 7340', 247) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (248, 'Team 7343', 248) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (249, 'Team 7347', 249) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (250, 'Team 7348', 250) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (251, 'Team 7349', 251) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (252, 'Team 7350', 252) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (253, 'Team 7351', 253) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (254, 'Team 7352', 254) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (255, 'Team 7354', 255) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (256, 'Team 75075', 256) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (257, 'Team 75076', 257) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (258, 'Team 75077', 258) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (259, 'Team 75182', 259) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (260, 'Team 75183', 260) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (261, 'Team 7679', 261) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (262, 'Team 77157', 262) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (263, 'Team 77487', 263) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (264, 'Team 77488', 264) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (265, 'Team 77491', 265) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (266, 'Team 77492', 266) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (267, 'Team 79987', 267) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (268, 'Team 8077', 268) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (269, 'Team 86861', 269) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (270, 'Team 88643', 270) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (271, 'Team 88644', 271) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (272, 'Team 88645', 272) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (273, 'Team 88646', 273) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (274, 'Team 88681', 274) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (275, 'Team 91900', 275) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (276, 'Team 91963', 276) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (277, 'Team 91964', 277) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (278, 'Team 91966', 278) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (279, 'Team 91967', 279) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (280, 'Team 91968', 280) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (281, 'Team 91969', 281) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (282, 'Team 91971', 282) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (283, 'Team 91972', 283) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (284, 'Team 92772', 284) ON CONFLICT (id) DO NOTHING;
INSERT INTO clubs (id, name, organization_id) VALUES (285, 'Team 93458', 285) ON CONFLICT (id) DO NOTHING;
