-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Teams - APSL
-- Total Records: 59
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (100, 'Falcons FC', '114814', 100, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (101, 'Scrub Nation', '118063', 101, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (102, 'Praia Kapital', '114837', 102, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (103, 'South Coast Union', '114844', 103, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (104, 'Project Football', '114838', 104, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (105, 'Invictus FC', '118064', 105, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (106, 'Fitchburg FC', '114815', 106, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (107, 'Somerville United FC', '131978', 107, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (108, 'KO Elites', '114826', 108, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (109, 'Glastonbury Celtic', '114816', 109, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (110, 'Wildcat FC', '114851', 110, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (111, 'Hermandad Connecticut', '114819', 111, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (112, 'Caribbean FCA', '135760', 112, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (113, 'NY Greek Americans', '114831', 113, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (114, 'Lansdowne Yonkers FC', '114827', 114, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (115, 'Hoboken FC 1912', '114820', 115, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (116, 'NY Pancyprian Freedoms', '114832', 116, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (117, 'Leros SC', '115315', 117, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (118, 'Doxa FCW', '114813', 118, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (119, 'NY International FC', '115102', 119, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (120, 'Richmond County FC', '114841', 120, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (121, 'Central Park Rangers FC', '114811', 121, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (122, 'SC Vistula Garfield', '114842', 122, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (123, 'Zum Schneider FC 03', '114852', 123, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (124, 'NY Athletic Club', '114830', 124, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (125, 'WC Predators', '114850', 125, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (126, 'Alloy Soccer Club', '114808', 126, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (127, 'Oaklyn United FC', '114833', 127, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (128, 'Real Central NJ Soccer', '114840', 128, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (129, 'Philadelphia Heritage SC', '114835', 129, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (130, 'Vidas United FC', '114847', 130, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (131, 'Philadelphia Soccer Club', '114836', 131, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (132, 'Jersey Shore Boca', '114822', 132, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (133, 'GAK', '124946', 133, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (134, 'Lighthouse 1893 SC', '116079', 134, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (135, 'Sewell Old Boys FC', '116136', 135, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (136, 'Medford Strikers', '115227', 136, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (137, 'Nova FC', '114829', 137, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (138, 'VA Marauders FC', '114846', 138, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (139, 'Wave FC', '114849', 139, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (140, 'PFA EPSL', '114834', 140, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (141, 'Grove Soccer United', '114817', 141, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (142, 'Christos FC', '114812', 142, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (143, 'Delmarva Thunder', '118680', 143, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (144, 'PW Nova', '114839', 144, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (145, 'Germantown City FC', '136127', 145, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (146, 'Terminus FC', '115815', 146, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (147, 'Prima FC', '115105', 147, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (148, 'Majestic SC', '115108', 148, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (149, 'Peachtree FC', '115101', 149, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (150, 'Bel Calcio FC', '115106', 150, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (151, 'Buckhead SC', '115104', 151, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (152, 'Alliance SC', '115107', 152, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (153, 'Georgia United FC', '133651', 153, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (154, 'SC Gwinnett', '119159', 154, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (155, 'AC Arlington FC', '136243', 155, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (156, 'Foro SC', '136241', 156, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (157, 'North Texas Prowl FC', '136240', 157, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (158, 'Texas Rage FC', '136242', 158, 1) ON CONFLICT (source_system_id, external_id) DO NOTHING;
