#!/bin/bash
# scripts/setup/setup-env.sh — env file template + Docker Hub login
set -e
source "$(dirname "$0")/_lib.sh"
REPO_ROOT="$(setup_repo_root)"
cd "$REPO_ROOT"

if [ ! -f env ]; then
  print_status "Creating fresh env template..."
  cat > env << 'EOF'
# Football Home Environment Variables (created by setup-env.sh)

ENVIRONMENT=dev
FRONTEND_URL=http://localhost:3000

# Docker Hub Authentication (avoid pull rate limits)
DOCKER_HUB_USERNAME=
DOCKER_HUB_TOKEN=

# Google OAuth (optional)
GOOGLE_OAUTH_CLIENT_ID=
GOOGLE_OAUTH_CLIENT_SECRET=
GOOGLE_OAUTH_REDIRECT_URI=http://localhost:3001/api/auth/google/callback
GOOGLE_OAUTH_EXTRA_SCOPES=

# JWT signing secret — rotate intentionally; changing it logs everyone out.
# Generate with: openssl rand -base64 48 | tr -d '\n'
JWT_SECRET=

# LeagueApps API Configuration (private API client id)
LEAGUEAPPS_API_PRIVATE_KEY=
LEAGUEAPPS_SITE_ID=
LEAGUEAPPS_MEMBERSHIP_PROGRAM_ID=
LEAGUEAPPS_BOYS_CLUB_PROGRAM_ID=
LEAGUEAPPS_GIRLS_CLUB_PROGRAM_ID=
LEAGUEAPPS_MENS_PROGRAM_ID=
LEAGUEAPPS_WOMENS_PROGRAM_ID=
LEAGUEAPPS_BOYS_PICKUP_PROGRAM_ID=
LEAGUEAPPS_GIRLS_PICKUP_PROGRAM_ID=
LEAGUEAPPS_MENS_PICKUP_PROGRAM_ID=
LEAGUEAPPS_WOMENS_PICKUP_PROGRAM_ID=
# Place files in config/ using this id as filename:
# config/<LEAGUEAPPS_API_PRIVATE_KEY>.p12
# config/<LEAGUEAPPS_API_PRIVATE_KEY>.pem (auto-generated by setup-env.sh when possible)

# Let's Encrypt — email used by certbot for renewal notices.
# When set, ./setup.sh will run `certbot --nginx --obtain-cert` automatically.
LE_EMAIL=

# Instagram + Meta Ads / Leadgen
INSTAGRAM_USER_ID=
INSTAGRAM_ACCESS_TOKEN=
META_INSTAGRAM_ACTOR_ID=
META_AD_ACCOUNT_ID=
META_PAGE_ID=
META_ADS_TOKEN=
META_LEADS_TOKEN=
META_LEADS_VERIFY_TOKEN=
META_LEAD_FORM_IDS=

# SMTP email delivery
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
MAIL_FROM=
MAIL_FROM_NAME="Football Home"

# Sim admin RPC + orchestrator
FH_SIM_ADMIN_TOKEN=
FH_SIM_ADMIN_URL=http://footballhome_sim:9101
FH_ENABLE_SIM_DEBUG=1
FH_SIM_ORCHESTRATOR_ENABLED=0

# Google Calendar service account sync
GCAL_SOCCER_CALENDAR_ID=
GCAL_OPS_CALENDAR_ID=
GCAL_SA_JSON=
EOF
  print_success "env file created"
else
  print_success "env file already exists"
fi

source ./env 2>/dev/null || true

# If LeagueApps key material exists, ensure PEM is available for JWT signing.
if [ -n "${LEAGUEAPPS_API_PRIVATE_KEY:-}" ]; then
  P12_FILE="config/${LEAGUEAPPS_API_PRIVATE_KEY}.p12"
  PEM_FILE="config/${LEAGUEAPPS_API_PRIVATE_KEY}.pem"
  if [ -f "$P12_FILE" ]; then
    if [ ! -f "$PEM_FILE" ] || [ "$P12_FILE" -nt "$PEM_FILE" ]; then
      print_status "Generating LeagueApps PEM from $(basename "$P12_FILE")..."
      if openssl pkcs12 -in "$P12_FILE" -nodes -passin pass:notasecret -out "$PEM_FILE" >/dev/null 2>&1; then
        chmod 600 "$PEM_FILE"
        print_success "LeagueApps PEM ready: $(basename "$PEM_FILE")"
      else
        print_warning "Failed to build LeagueApps PEM from $(basename "$P12_FILE")"
      fi
    else
      print_success "LeagueApps PEM already up to date"
    fi
  else
    print_warning "LeagueApps P12 not found: $P12_FILE"
  fi
fi

# Docker Hub login
if podman login --get-login docker.io &> /dev/null; then
  print_success "Already logged in to Docker Hub as: $(podman login --get-login docker.io)"
else
  source ./env 2>/dev/null || true
  if [ -n "$DOCKER_HUB_USERNAME" ] && [ -n "$DOCKER_HUB_TOKEN" ]; then
    print_status "Logging in to Docker Hub from env file..."
    if echo "$DOCKER_HUB_TOKEN" | podman login docker.io -u "$DOCKER_HUB_USERNAME" --password-stdin &> /dev/null; then
      print_success "Logged in to Docker Hub"
    else
      print_warning "Docker Hub login failed — check env credentials"
    fi
  else
    print_warning "No Docker Hub credentials in env (optional, raises pull rate limit)"
  fi
fi
