-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Organizations - APSL
-- Total Records: 76
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO organizations (id, name) SELECT 100, 'KO Elites' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'KO Elites') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 101, 'Glastonbury Celtic' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Glastonbury Celtic') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 102, 'Wildcat FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Wildcat FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 103, 'Caribbean FCA' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Caribbean FCA') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 104, 'Hermandad Connecticut' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Hermandad Connecticut') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 105, 'WC Predators' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'WC Predators') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 106, 'Alloy Soccer Club' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Alloy Soccer Club') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 107, 'Oaklyn United FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Oaklyn United FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 108, 'Real Central NJ Soccer' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Real Central NJ Soccer') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 109, 'Philadelphia Soccer Club' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Philadelphia Soccer Club') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 110, 'Philadelphia Heritage SC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Philadelphia Heritage SC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 111, 'Jersey Shore Boca' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Jersey Shore Boca') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 112, 'Vidas United FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Vidas United FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 113, 'Lighthouse 1893 SC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Lighthouse 1893 SC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 114, 'GAK' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'GAK') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 115, 'Sewell Old Boys FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Sewell Old Boys FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 116, 'Medford Strikers' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Medford Strikers') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 117, 'Scrub Nation' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Scrub Nation') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 118, 'Praia Kapital' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Praia Kapital') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 119, 'Falcons FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Falcons FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 120, 'South Coast Union' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'South Coast Union') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 121, 'Project Football' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Project Football') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 122, 'Somerville United FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Somerville United FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 123, 'Invictus FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Invictus FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 124, 'Fitchburg FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Fitchburg FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 125, 'NY Greek Americans' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'NY Greek Americans') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 126, 'Lansdowne Yonkers FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Lansdowne Yonkers FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 127, 'NY Pancyprian Freedoms' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'NY Pancyprian Freedoms') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 128, 'Hoboken FC 1912' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Hoboken FC 1912') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 129, 'Doxa FCW' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Doxa FCW') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 130, 'Leros SC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Leros SC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 131, 'Richmond County FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Richmond County FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 132, 'NY International FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'NY International FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 133, 'SC Vistula Garfield' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'SC Vistula Garfield') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 134, 'Zum Schneider FC 03' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Zum Schneider FC 03') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 135, 'NY Athletic Club' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'NY Athletic Club') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 136, 'Central Park Rangers FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Central Park Rangers FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 137, 'Nova FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Nova FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 138, 'VA Marauders FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'VA Marauders FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 139, 'Wave FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Wave FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 140, 'PFA APSL' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'PFA APSL') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 141, 'Grove Soccer' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Grove Soccer') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 142, 'Christos FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Christos FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 143, 'Delmarva Thunder' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Delmarva Thunder') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 144, 'PW Nova' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'PW Nova') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 145, 'Club Petrolero' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Club Petrolero') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 146, 'Baltimore City FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Baltimore City FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 147, 'DMV Rangers' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'DMV Rangers') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 148, 'Baltimore City Academy' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Baltimore City Academy') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 149, 'Chiefs' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Chiefs') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 150, 'Germantown City FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Germantown City FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 151, 'Alianza FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Alianza FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 152, 'Cavaliers United FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Cavaliers United FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 153, 'Drita SC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Drita SC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 154, 'Hoverla FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Hoverla FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 155, 'Imlay City FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Imlay City FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 156, 'Inter Detroit' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Inter Detroit') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 157, 'Intra United SC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Intra United SC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 158, 'Livonia City FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Livonia City FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 159, 'Monroe' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Monroe') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 160, 'World Class FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'World Class FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 161, 'Majestic SC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Majestic SC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 162, 'Terminus FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Terminus FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 163, 'Prima FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Prima FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 164, 'Peachtree FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Peachtree FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 165, 'Bel Calcio FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Bel Calcio FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 166, 'Georgia United FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Georgia United FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 167, 'Buckhead SC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Buckhead SC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 168, 'Alliance SC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Alliance SC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 169, 'SC Gwinnett' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'SC Gwinnett') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 170, 'Foro SC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Foro SC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 171, 'Carrollton Old Boyz' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Carrollton Old Boyz') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 172, 'AC Arlington FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'AC Arlington FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 173, 'Texas Coyotes' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Texas Coyotes') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 174, 'Texas Rage FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Texas Rage FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 175, 'Philadelphia SC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Philadelphia SC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
