-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Organizations - APSL
-- Total Records: 59
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO organizations (id, name) VALUES (100, 'Falcons FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (101, 'Scrub Nation') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (102, 'Praia Kapital') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (103, 'South Coast Union') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (104, 'Project Football') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (105, 'Invictus FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (106, 'Fitchburg FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (107, 'Somerville United FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (108, 'KO Elites') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (109, 'Glastonbury Celtic') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (110, 'Wildcat FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (111, 'Hermandad Connecticut') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (112, 'Caribbean FCA') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (113, 'NY Greek Americans') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (114, 'Lansdowne Yonkers FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (115, 'Hoboken FC 1912') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (116, 'NY Pancyprian Freedoms') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (117, 'Leros SC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (118, 'Doxa FCW') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (119, 'NY International FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (120, 'Richmond County FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (121, 'Central Park Rangers FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (122, 'SC Vistula Garfield') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (123, 'Zum Schneider FC 03') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (124, 'NY Athletic Club') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (125, 'WC Predators') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (126, 'Alloy Soccer Club') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (127, 'Oaklyn United FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (128, 'Real Central NJ Soccer') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (129, 'Philadelphia Heritage SC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (130, 'Vidas United FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (131, 'Philadelphia Soccer Club') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (132, 'Jersey Shore Boca') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (133, 'GAK') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (134, 'Lighthouse 1893 SC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (135, 'Sewell Old Boys FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (136, 'Medford Strikers') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (137, 'Nova FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (138, 'VA Marauders FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (139, 'Wave FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (140, 'PFA EPSL') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (141, 'Grove Soccer') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (142, 'Christos FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (143, 'Delmarva Thunder') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (144, 'PW Nova') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (145, 'Germantown City FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (146, 'Terminus FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (147, 'Prima FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (148, 'Majestic SC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (149, 'Peachtree FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (150, 'Bel Calcio FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (151, 'Buckhead SC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (152, 'Alliance SC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (153, 'Georgia United FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (154, 'SC Gwinnett') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (155, 'AC Arlington FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (156, 'Foro SC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (157, 'North Texas Prowl FC') ON CONFLICT (id) DO NOTHING;
INSERT INTO organizations (id, name) VALUES (158, 'Texas Rage FC') ON CONFLICT (id) DO NOTHING;
