-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Clubs - APSL
-- Total Records: 53
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO clubs (id, name, organization_id) VALUES (100, 'Falcons FC', (SELECT id FROM organizations WHERE name = 'Falcons FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (101, 'Scrub Nation', (SELECT id FROM organizations WHERE name = 'Scrub Nation')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (102, 'Praia Kapital', (SELECT id FROM organizations WHERE name = 'Praia Kapital')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (103, 'South Coast Union', (SELECT id FROM organizations WHERE name = 'South Coast Union')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (104, 'Project Football', (SELECT id FROM organizations WHERE name = 'Project Football')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (105, 'Invictus FC', (SELECT id FROM organizations WHERE name = 'Invictus FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (106, 'Fitchburg FC', (SELECT id FROM organizations WHERE name = 'Fitchburg FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (107, 'Somerville United FC', (SELECT id FROM organizations WHERE name = 'Somerville United FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (108, 'KO Elites', (SELECT id FROM organizations WHERE name = 'KO Elites')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (109, 'Glastonbury Celtic', (SELECT id FROM organizations WHERE name = 'Glastonbury Celtic')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (110, 'Wildcat FC', (SELECT id FROM organizations WHERE name = 'Wildcat FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (111, 'Hermandad Connecticut', (SELECT id FROM organizations WHERE name = 'Hermandad Connecticut')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (112, 'NY Greek Americans', (SELECT id FROM organizations WHERE name = 'NY Greek Americans')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (113, 'Hoboken FC 1912', (SELECT id FROM organizations WHERE name = 'Hoboken FC 1912')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (114, 'NY Pancyprian Freedoms', (SELECT id FROM organizations WHERE name = 'NY Pancyprian Freedoms')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (115, 'Lansdowne Yonkers FC', (SELECT id FROM organizations WHERE name = 'Lansdowne Yonkers FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (116, 'Doxa FCW', (SELECT id FROM organizations WHERE name = 'Doxa FCW')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (117, 'Leros SC', (SELECT id FROM organizations WHERE name = 'Leros SC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (118, 'NY International FC', (SELECT id FROM organizations WHERE name = 'NY International FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (119, 'Richmond County FC', (SELECT id FROM organizations WHERE name = 'Richmond County FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (120, 'Zum Schneider FC 03', (SELECT id FROM organizations WHERE name = 'Zum Schneider FC 03')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (121, 'Central Park Rangers FC', (SELECT id FROM organizations WHERE name = 'Central Park Rangers FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (122, 'SC Vistula Garfield', (SELECT id FROM organizations WHERE name = 'SC Vistula Garfield')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (123, 'NY Athletic Club', (SELECT id FROM organizations WHERE name = 'NY Athletic Club')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (124, 'WC Predators', (SELECT id FROM organizations WHERE name = 'WC Predators')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (125, 'Alloy Soccer Club', (SELECT id FROM organizations WHERE name = 'Alloy Soccer Club')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (126, 'Oaklyn United FC', (SELECT id FROM organizations WHERE name = 'Oaklyn United FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (127, 'Real Central NJ Soccer', (SELECT id FROM organizations WHERE name = 'Real Central NJ Soccer')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (128, 'Philadelphia Heritage SC', (SELECT id FROM organizations WHERE name = 'Philadelphia Heritage SC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (129, 'Philadelphia Soccer Club', (SELECT id FROM organizations WHERE name = 'Philadelphia Soccer Club')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (130, 'Vidas United FC', (SELECT id FROM organizations WHERE name = 'Vidas United FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (131, 'GAK', (SELECT id FROM organizations WHERE name = 'GAK')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (132, 'Lighthouse 1893 SC', (SELECT id FROM organizations WHERE name = 'Lighthouse 1893 SC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (133, 'Jersey Shore Boca', (SELECT id FROM organizations WHERE name = 'Jersey Shore Boca')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (134, 'Sewell Old Boys FC', (SELECT id FROM organizations WHERE name = 'Sewell Old Boys FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (135, 'Medford Strikers', (SELECT id FROM organizations WHERE name = 'Medford Strikers')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (136, 'Nova FC', (SELECT id FROM organizations WHERE name = 'Nova FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (137, 'VA Marauders FC', (SELECT id FROM organizations WHERE name = 'VA Marauders FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (138, 'Wave FC', (SELECT id FROM organizations WHERE name = 'Wave FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (139, 'PFA EPSL', (SELECT id FROM organizations WHERE name = 'PFA EPSL')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (140, 'Grove Soccer', (SELECT id FROM organizations WHERE name = 'Grove Soccer')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (141, 'Christos FC', (SELECT id FROM organizations WHERE name = 'Christos FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (142, 'Delmarva Thunder', (SELECT id FROM organizations WHERE name = 'Delmarva Thunder')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (143, 'PW Nova', (SELECT id FROM organizations WHERE name = 'PW Nova')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (144, 'Terminus FC', (SELECT id FROM organizations WHERE name = 'Terminus FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (145, 'Prima FC', (SELECT id FROM organizations WHERE name = 'Prima FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (146, 'Majestic SC', (SELECT id FROM organizations WHERE name = 'Majestic SC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (147, 'Peachtree FC', (SELECT id FROM organizations WHERE name = 'Peachtree FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (148, 'Bel Calcio FC', (SELECT id FROM organizations WHERE name = 'Bel Calcio FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (149, 'Buckhead SC', (SELECT id FROM organizations WHERE name = 'Buckhead SC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (150, 'Alliance SC', (SELECT id FROM organizations WHERE name = 'Alliance SC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (151, 'SC Gwinnett', (SELECT id FROM organizations WHERE name = 'SC Gwinnett')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) VALUES (152, 'Georgia United FC', (SELECT id FROM organizations WHERE name = 'Georgia United FC')) ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
