-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Organizations - CSL
-- Total Records: 55
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO organizations (id, name) SELECT 10000, 'FC Sandzak' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'FC Sandzak') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10001, 'Block FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Block FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10002, 'Manhattan Kickers' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Manhattan Kickers') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10003, 'Polonia SC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Polonia SC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10004, 'NY Ukrainians' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'NY Ukrainians') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10005, 'Hoboken FC 1912' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Hoboken FC 1912') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10006, 'Laberia FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Laberia FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10007, 'Central Park Rangers' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Central Park Rangers') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10008, 'Manhattan Celtic' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Manhattan Celtic') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10009, 'Zum Schneider FC 03' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Zum Schneider FC 03') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10010, 'FC Ulqini' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'FC Ulqini') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10011, 'NY International FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'NY International FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10012, 'Brooklyn City FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Brooklyn City FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10013, 'Stal Mielec NY' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Stal Mielec NY') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10014, 'Vibes FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Vibes FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10015, 'NY Galicia' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'NY Galicia') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10016, 'NY Shamrocks' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'NY Shamrocks') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10017, 'NY Finest FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'NY Finest FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10018, 'Sporting Astoria South Bronx' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Sporting Astoria South Bronx') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10019, 'ERFC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'ERFC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10020, 'Williamsburg International FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Williamsburg International FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10021, 'FC Japan' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'FC Japan') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10022, 'SC Eintracht' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'SC Eintracht') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10023, 'Kickoff FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Kickoff FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10024, 'Yemen United SC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Yemen United SC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10025, 'Vllaznia NYC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Vllaznia NYC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10026, 'Desportiva Sociedad NY' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Desportiva Sociedad NY') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10027, 'Braza Futbol' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Braza Futbol') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10028, 'SC Football Crew' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'SC Football Crew') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10029, 'NY Athletic Club' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'NY Athletic Club') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10030, 'Sporting Astoria SBU' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Sporting Astoria SBU') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10031, 'FanDuel FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'FanDuel FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10032, 'Aurora FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Aurora FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10033, 'Riverside Squires' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Riverside Squires') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10034, 'Panatha USA' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Panatha USA') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10035, 'Junior Mafia FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Junior Mafia FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10036, 'NY Legacy FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'NY Legacy FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10037, 'C.A. Islas Malvinas' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'C.A. Islas Malvinas') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10038, 'Ollama FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Ollama FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10039, 'Barnstonworth Rovers FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Barnstonworth Rovers FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10040, 'Warriors NYC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Warriors NYC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10041, 'NY Titans FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'NY Titans FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10042, 'NYC AlphaStars Club' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'NYC AlphaStars Club') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10043, 'Al-Asad' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Al-Asad') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10044, 'SC Gjoa' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'SC Gjoa') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10045, 'Brooklyn New York SC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Brooklyn New York SC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10046, 'Pelham Parkway FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Pelham Parkway FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10047, 'Bolivia Si Existe FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Bolivia Si Existe FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10048, 'Desportiva Sociedad NY Samba' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Desportiva Sociedad NY Samba') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10049, 'FC Hudson' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'FC Hudson') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10050, 'FC Kraja' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'FC Kraja') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10051, 'FC Rush' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'FC Rush') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10052, 'Tiercel City FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Tiercel City FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10053, 'Cozmoz FC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Cozmoz FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO organizations (id, name) SELECT 10054, 'Polonez SC' WHERE NOT EXISTS (SELECT 1 FROM organizations WHERE name = 'Polonez SC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name;
