-- ========================================
-- APSL LEAGUE STRUCTURE (AUTO-GENERATED)
-- ========================================
-- Generated: [Will be populated by scraper]
-- Source: https://apslsoccer.com/standings/
-- Includes: Leagues, Conferences, Divisions, Clubs, Sport Divisions, Teams
-- DOES NOT include: Player rosters (see 02-player-rosters.sql)
--
-- This file is automatically regenerated on rebuild if APSL_SCRAPE=true
-- ========================================

-- TODO: Populate this with league structure data from apsl-data.sql
-- Currently, the full apsl-data.sql includes both structure and players
-- This needs to be split by the scraper script

-- Placeholder: Will contain INSERT statements for:
-- - leagues (APSL)
-- - league_conferences (Mayflower, Constitution, Metropolitan, Delaware River, Mid-Atlantic, Terminus)
-- - league_divisions (divisions within conferences)
-- - clubs (all APSL clubs including Lighthouse 1893 SC)
-- - sport_divisions (club's sport divisions)
-- - teams (team entities without player rosters)
