#!/usr/bin/env node

/**
 * APSL SQL Curator
 * 
 * Pass-through curator for APSL league data.
 * Since APSL is typically the first league loaded, there are usually no
 * pre-existing clubs to match against. However, this curator provides the
 * same interface as other leagues for consistency and flexibility if load
 * order changes in the future.
 * 
 * Workflow:
 * 1. Read APSL SQL files (generated by generate-sql.js)
 * 2. Check for any pre-existing clubs from other leagues
 * 3. Match APSL clubs to existing clubs if found (rare scenario)
 * 4. Generate curated SQL (typically identical to input)
 * 5. Write back to same SQL files
 */

const path = require('path');
const fs = require('fs');
const BaseSqlCurator = require('../../../BaseSqlCurator');

class ApslSqlCurator extends BaseSqlCurator {
  constructor() {
    super();
    this.config = JSON.parse(fs.readFileSync(path.join(__dirname, 'config.json'), 'utf8'));
    this.sourceSystemId = this.config.sourceSystemId;
    this.sqlDir = path.join(__dirname, 'sql');
  }

  /**
   * Define APSL club family mappings from config
   */
  getClubFamily(clubBaseName) {
    return this.config.clubFamilies[clubBaseName.toLowerCase()] || null;
  }

  /**
   * Curate APSL SQL files
   * Checks for pre-existing clubs and matches where possible
   */
  async curate() {
    console.log('\n=== APSL SQL Curation ===\n');
    
    // Read APSL SQL files (our newly generated data)
    const fc = this.config.fileCode;
    const slug = this.config.leagueSlug;
    const apslOrgsFile = path.join(this.sqlDir, `100.${fc}-organizations-${slug}.sql`);
    const apslClubsFile = path.join(this.sqlDir, `101.${fc}-clubs-${slug}.sql`);
    const apslTeamsFile = path.join(this.sqlDir, `102.${fc}-teams-${slug}.sql`);
    
    if (!fs.existsSync(apslOrgsFile)) {
      console.log('No APSL SQL files found. Run generate-sql.js first.');
      return;
    }
    
    const apslOrgsSql = fs.readFileSync(apslOrgsFile, 'utf8');
    const apslClubsSql = fs.readFileSync(apslClubsFile, 'utf8');
    const apslTeamsSql = fs.readFileSync(apslTeamsFile, 'utf8');
    
    // Parse APSL data
    const apslOrgs = this.parseOrganizationsSql(apslOrgsSql);
    const apslClubs = this.parseClubsSql(apslClubsSql);
    const apslTeams = this.parseTeamsSql(apslTeamsSql);
    
    console.log(`Parsed ${apslOrgs.length} organizations, ${apslClubs.length} clubs, ${apslTeams.length} teams from APSL SQL\n`);
    
    // APSL is always the baseline - no curation needed
    console.log('APSL is the baseline league - no curation needed.');
    console.log('SQL passed through unchanged:');
    console.log(`  - ${apslOrgs.length} organizations`);
    console.log(`  - ${apslClubs.length} clubs`);
    console.log(`  - ${apslTeams.length} teams\n`);
    return; // Skip all curation logic
    
    for (const league of otherLeagues) {
      const leagueClubsFile = path.join(leaguesDir, league, 'sql', `101.*-clubs-${league}.sql`);
      const matches = require('glob').sync(leagueClubsFile);
      
      if (matches.length > 0) {
        const otherClubsSql = fs.readFileSync(matches[0], 'utf8');
        const otherClubs = this.parseClubsSql(otherClubsSql);
        existingClubs.push(...otherClubs);
        console.log(`Found ${otherClubs.length} existing clubs from ${league}`);
      }
    }
    
    if (existingClubs.length === 0) {
      console.log('No pre-existing clubs found from other leagues.');
      console.log('APSL is the first league loaded - no curation needed.\n');
      console.log('Curated SQL (pass-through):');
      console.log(`  - ${apslOrgs.length} organizations`);
      console.log(`  - ${apslClubs.length} clubs`);
      console.log(`  - ${apslTeams.length} teams\n`);
      return; // No changes needed
    }
    
    // If we found pre-existing clubs, match APSL clubs to them
    console.log(`\nMatching ${apslClubs.length} APSL clubs against ${existingClubs.length} existing clubs...\n`);
    
    const matches = [];
    for (const apslClub of apslClubs) {
      const match = this.findMatchingClub(apslClub.name, existingClubs);
      if (match) {
        matches.push({
          apslClub,
          existingClub: match
        });
        console.log(`  ✓ "${apslClub.name}" → existing club "${match.name}" (id=${match.id})`);
      }
    }
    
    if (matches.length === 0) {
      console.log('No matches found. APSL clubs are unique.\n');
      return; // No changes needed
    }
    
    // Generate curated SQL
    console.log(`\nGenerating curated SQL with ${matches.length} matched clubs...\n`);
    
    const curatedOrgsSql = this.generateCuratedOrganizationsSql(apslOrgs, apslClubs, matches);
    const curatedClubsSql = this.generateCuratedClubsSql(apslClubs, matches);
    const curatedTeamsSql = this.generateCuratedTeamsSql(apslTeams, apslClubs, matches);
    
    // Write curated SQL back to files
    fs.writeFileSync(apslOrgsFile, curatedOrgsSql);
    fs.writeFileSync(apslClubsFile, curatedClubsSql);
    fs.writeFileSync(apslTeamsFile, curatedTeamsSql);
    
    console.log('Curated SQL written:');
    console.log(`  - ${apslOrgsFile}`);
    console.log(`  - ${apslClubsFile}`);
    console.log(`  - ${apslTeamsFile}\n`);
  }

  /**
   * Generate curated organizations SQL
   * Only create orgs for new APSL-only clubs
   */
  generateCuratedOrganizationsSql(orgs, clubs, matches) {
    const matchedClubIds = new Set(matches.map(m => m.apslClub.id));
    const newOrgs = orgs.filter(org => {
      // Find clubs for this org
      const orgClubs = clubs.filter(c => c.organizationId === org.id);
      // Keep org only if it has at least one unmatched club
      return orgClubs.some(c => !matchedClubIds.has(c.id));
    });
    
    let sql = '-- APSL Organizations (Curated)\n\n';
    for (const org of newOrgs) {
      sql += `INSERT INTO organizations (id, name) VALUES (${org.id}, '${org.name}') ON CONFLICT (id) DO NOTHING;\n`;
    }
    return sql;
  }

  /**
   * Generate curated clubs SQL
   * Skip matched clubs (use existing club IDs)
   */
  generateCuratedClubsSql(clubs, matches) {
    const matchedClubIds = new Set(matches.map(m => m.apslClub.id));
    const newClubs = clubs.filter(c => !matchedClubIds.has(c.id));
    
    let sql = '-- APSL Clubs (Curated)\n\n';
    for (const club of newClubs) {
      sql += `INSERT INTO clubs (id, name, organization_id) VALUES (${club.id}, '${club.name}', ${club.organizationId}) ON CONFLICT (id) DO NOTHING;\n`;
    }
    return sql;
  }

  /**
   * Generate curated teams SQL
   * Use existing club_id for matched teams
   */
  generateCuratedTeamsSql(teams, clubs, matches) {
    const clubIdMap = new Map(matches.map(m => [m.apslClub.id, m.existingClub.id]));
    
    let sql = '-- APSL Teams (Curated)\n\n';
    for (const team of teams) {
      const curatedClubId = clubIdMap.get(team.clubId) || team.clubId;
      sql += `INSERT INTO teams (id, name, external_id, club_id, source_system_id) VALUES (${team.id}, '${team.name}', '${team.externalId}', ${curatedClubId}, ${team.sourceSystemId}) ON CONFLICT (external_id, source_system_id) DO NOTHING;\n`;
    }
    return sql;
  }
}

// Run curator
const curator = new ApslSqlCurator();
curator.curate().catch(err => {
  console.error('Curation failed:', err);
  process.exit(1);
});
