-- APSL Teams (Scraped Data)
-- Generated by database-driven scraper from apslsoccer.com
-- Uses CTEs with RETURNING to get auto-generated IDs
-- external_id stored in team_divisions (source-specific relationship)

WITH inserted_teams AS (
  INSERT INTO teams (name) VALUES
    ('Falcons FC'),
    ('Scrub Nation'),
    ('Praia Kapital'),
    ('South Coast Union'),
    ('Project Football'),
    ('Invictus FC'),
    ('Fitchburg FC'),
    ('Somerville United FC'),
    ('KO Elites'),
    ('Glastonbury Celtic'),
    ('Wildcat FC'),
    ('Hermandad Connecticut'),
    ('NY Greek Americans'),
    ('Hoboken FC 1912'),
    ('NY Pancyprian Freedoms'),
    ('Lansdowne Yonkers FC'),
    ('Doxa FCW'),
    ('Leros SC'),
    ('NY International FC'),
    ('Richmond County FC'),
    ('Zum Schneider FC 03'),
    ('Central Park Rangers FC'),
    ('SC Vistula Garfield'),
    ('NY Athletic Club'),
    ('WC Predators'),
    ('Alloy Soccer Club'),
    ('Oaklyn United FC'),
    ('Real Central NJ Soccer'),
    ('Philadelphia Heritage SC'),
    ('Philadelphia Soccer Club'),
    ('Vidas United FC'),
    ('GAK'),
    ('Lighthouse 1893 SC'),
    ('Jersey Shore Boca'),
    ('Sewell Old Boys FC'),
    ('Medford Strikers'),
    ('Nova FC'),
    ('VA Marauders FC'),
    ('Wave FC'),
    ('PFA EPSL'),
    ('Grove Soccer United'),
    ('Christos FC'),
    ('Delmarva Thunder'),
    ('PW Nova'),
    ('Terminus FC'),
    ('Prima FC'),
    ('Majestic SC'),
    ('Peachtree FC'),
    ('Bel Calcio FC'),
    ('Buckhead SC'),
    ('Alliance SC'),
    ('SC Gwinnett')
  ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
  RETURNING id, name
)
INSERT INTO team_divisions (team_id, division_id, source_system_id, external_id, is_active)
SELECT
  it.id,
  CASE it.name
    WHEN 'Falcons FC' THEN 1
    WHEN 'Scrub Nation' THEN 1
    WHEN 'Praia Kapital' THEN 1
    WHEN 'South Coast Union' THEN 1
    WHEN 'Project Football' THEN 1
    WHEN 'Invictus FC' THEN 1
    WHEN 'Fitchburg FC' THEN 1
    WHEN 'Somerville United FC' THEN 1
    WHEN 'KO Elites' THEN 2
    WHEN 'Glastonbury Celtic' THEN 2
    WHEN 'Wildcat FC' THEN 2
    WHEN 'Hermandad Connecticut' THEN 2
    WHEN 'NY Greek Americans' THEN 3
    WHEN 'Hoboken FC 1912' THEN 3
    WHEN 'NY Pancyprian Freedoms' THEN 3
    WHEN 'Lansdowne Yonkers FC' THEN 3
    WHEN 'Doxa FCW' THEN 3
    WHEN 'Leros SC' THEN 3
    WHEN 'NY International FC' THEN 3
    WHEN 'Richmond County FC' THEN 3
    WHEN 'Zum Schneider FC 03' THEN 3
    WHEN 'Central Park Rangers FC' THEN 3
    WHEN 'SC Vistula Garfield' THEN 3
    WHEN 'NY Athletic Club' THEN 3
    WHEN 'WC Predators' THEN 4
    WHEN 'Alloy Soccer Club' THEN 4
    WHEN 'Oaklyn United FC' THEN 4
    WHEN 'Real Central NJ Soccer' THEN 4
    WHEN 'Philadelphia Heritage SC' THEN 4
    WHEN 'Philadelphia Soccer Club' THEN 4
    WHEN 'Vidas United FC' THEN 4
    WHEN 'GAK' THEN 4
    WHEN 'Lighthouse 1893 SC' THEN 4
    WHEN 'Jersey Shore Boca' THEN 4
    WHEN 'Sewell Old Boys FC' THEN 4
    WHEN 'Medford Strikers' THEN 4
    WHEN 'Nova FC' THEN 5
    WHEN 'VA Marauders FC' THEN 5
    WHEN 'Wave FC' THEN 5
    WHEN 'PFA EPSL' THEN 5
    WHEN 'Grove Soccer United' THEN 5
    WHEN 'Christos FC' THEN 5
    WHEN 'Delmarva Thunder' THEN 5
    WHEN 'PW Nova' THEN 5
    WHEN 'Terminus FC' THEN 6
    WHEN 'Prima FC' THEN 6
    WHEN 'Majestic SC' THEN 6
    WHEN 'Peachtree FC' THEN 6
    WHEN 'Bel Calcio FC' THEN 6
    WHEN 'Buckhead SC' THEN 6
    WHEN 'Alliance SC' THEN 6
    WHEN 'SC Gwinnett' THEN 6
  END,
  1,  -- source_system_id (APSL)
  CASE it.name
    WHEN 'Falcons FC' THEN '114814'
    WHEN 'Scrub Nation' THEN '118063'
    WHEN 'Praia Kapital' THEN '114837'
    WHEN 'South Coast Union' THEN '114844'
    WHEN 'Project Football' THEN '114838'
    WHEN 'Invictus FC' THEN '118064'
    WHEN 'Fitchburg FC' THEN '114815'
    WHEN 'Somerville United FC' THEN '131978'
    WHEN 'KO Elites' THEN '114826'
    WHEN 'Glastonbury Celtic' THEN '114816'
    WHEN 'Wildcat FC' THEN '114851'
    WHEN 'Hermandad Connecticut' THEN '114819'
    WHEN 'NY Greek Americans' THEN '114831'
    WHEN 'Hoboken FC 1912' THEN '114820'
    WHEN 'NY Pancyprian Freedoms' THEN '114832'
    WHEN 'Lansdowne Yonkers FC' THEN '114827'
    WHEN 'Doxa FCW' THEN '114813'
    WHEN 'Leros SC' THEN '115315'
    WHEN 'NY International FC' THEN '115102'
    WHEN 'Richmond County FC' THEN '114841'
    WHEN 'Zum Schneider FC 03' THEN '114852'
    WHEN 'Central Park Rangers FC' THEN '114811'
    WHEN 'SC Vistula Garfield' THEN '114842'
    WHEN 'NY Athletic Club' THEN '114830'
    WHEN 'WC Predators' THEN '114850'
    WHEN 'Alloy Soccer Club' THEN '114808'
    WHEN 'Oaklyn United FC' THEN '114833'
    WHEN 'Real Central NJ Soccer' THEN '114840'
    WHEN 'Philadelphia Heritage SC' THEN '114835'
    WHEN 'Philadelphia Soccer Club' THEN '114836'
    WHEN 'Vidas United FC' THEN '114847'
    WHEN 'GAK' THEN '124946'
    WHEN 'Lighthouse 1893 SC' THEN '116079'
    WHEN 'Jersey Shore Boca' THEN '114822'
    WHEN 'Sewell Old Boys FC' THEN '116136'
    WHEN 'Medford Strikers' THEN '115227'
    WHEN 'Nova FC' THEN '114829'
    WHEN 'VA Marauders FC' THEN '114846'
    WHEN 'Wave FC' THEN '114849'
    WHEN 'PFA EPSL' THEN '114834'
    WHEN 'Grove Soccer United' THEN '114817'
    WHEN 'Christos FC' THEN '114812'
    WHEN 'Delmarva Thunder' THEN '118680'
    WHEN 'PW Nova' THEN '114839'
    WHEN 'Terminus FC' THEN '115815'
    WHEN 'Prima FC' THEN '115105'
    WHEN 'Majestic SC' THEN '115108'
    WHEN 'Peachtree FC' THEN '115101'
    WHEN 'Bel Calcio FC' THEN '115106'
    WHEN 'Buckhead SC' THEN '115104'
    WHEN 'Alliance SC' THEN '115107'
    WHEN 'SC Gwinnett' THEN '119159'
  END,
  true
FROM inserted_teams it
ON CONFLICT (team_id, division_id) DO UPDATE SET
  external_id = EXCLUDED.external_id,
  is_active = EXCLUDED.is_active;

-- TODO: Store standings stats (GP, W, T, L, GF, GA, Pts) in team_stats table
