-- Clubs (scraped data)
-- Generated by ApslScraper + CasaScraper
-- Combined APSL + CASA clubs in single file
-- Differentiated by source_system_id (1=APSL, 2=CASA)

-- This file is generated by scrapers and committed to git for reproducibility
-- To regenerate: ./dev.sh --refresh
