-- Clubs (Football Home club data + scraped teams)
-- Each team gets its own club by default (can consolidate later in UI)
-- This file is generated by scrapers and committed to git

INSERT INTO clubs (id, display_name, slug, is_active) VALUES
    (1, 'Lighthouse 1893 SC', 'lighthouse-1893', true)
,
    (2, 'Falcons FC', 'falcons-fc', true)
,
    (3, 'Scrub Nation', 'scrub-nation', true)
,
    (4, 'Praia Kapital', 'praia-kapital', true)
,
    (5, 'South Coast Union', 'south-coast-union', true)
,
    (6, 'Project Football', 'project-football', true)
,
    (7, 'Invictus FC', 'invictus-fc', true)
,
    (8, 'Fitchburg FC', 'fitchburg-fc', true)
,
    (9, 'Somerville United FC', 'somerville-united-fc', true)
,
    (10, 'KO Elites', 'ko-elites', true)
,
    (11, 'Glastonbury Celtic', 'glastonbury-celtic', true)
,
    (12, 'Wildcat FC', 'wildcat-fc', true)
,
    (13, 'Hermandad Connecticut', 'hermandad-connecticut', true)
,
    (14, 'NY Greek Americans', 'ny-greek-americans', true)
,
    (15, 'Hoboken FC 1912', 'hoboken-fc-1912', true)
,
    (16, 'NY Pancyprian Freedoms', 'ny-pancyprian-freedoms', true)
,
    (17, 'Lansdowne Yonkers FC', 'lansdowne-yonkers-fc', true)
,
    (18, 'Doxa FCW', 'doxa-fcw', true)
,
    (19, 'Leros SC', 'leros-sc', true)
,
    (20, 'NY International FC', 'ny-international-fc', true)
,
    (21, 'Richmond County FC', 'richmond-county-fc', true)
,
    (22, 'Zum Schneider FC 03', 'zum-schneider-fc-03', true)
,
    (23, 'Central Park Rangers FC', 'central-park-rangers-fc', true)
,
    (24, 'SC Vistula Garfield', 'sc-vistula-garfield', true)
,
    (25, 'NY Athletic Club', 'ny-athletic-club', true)
,
    (26, 'WC Predators', 'wc-predators', true)
,
    (27, 'Alloy Soccer Club', 'alloy-soccer-club', true)
,
    (28, 'Oaklyn United FC', 'oaklyn-united-fc', true)
,
    (29, 'Real Central NJ Soccer', 'real-central-nj-soccer', true)
,
    (30, 'Philadelphia Heritage SC', 'philadelphia-heritage-sc', true)
,
    (31, 'Philadelphia Soccer Club', 'philadelphia-soccer-club', true)
,
    (32, 'Vidas United FC', 'vidas-united-fc', true)
,
    (33, 'GAK', 'gak', true)
,
    (34, 'Lighthouse 1893 SC', 'lighthouse-1893-sc', true)
,
    (35, 'Jersey Shore Boca', 'jersey-shore-boca', true)
,
    (36, 'Sewell Old Boys FC', 'sewell-old-boys-fc', true)
,
    (37, 'Medford Strikers', 'medford-strikers', true)
,
    (38, 'Nova FC', 'nova-fc', true)
,
    (39, 'VA Marauders FC', 'va-marauders-fc', true)
,
    (40, 'Wave FC', 'wave-fc', true)
,
    (41, 'PFA EPSL', 'pfa-epsl', true)
,
    (42, 'Grove Soccer United', 'grove-soccer-united', true)
,
    (43, 'Christos FC', 'christos-fc', true)
,
    (44, 'Delmarva Thunder', 'delmarva-thunder', true)
,
    (45, 'PW Nova', 'pw-nova', true)
,
    (46, 'Terminus FC', 'terminus-fc', true)
,
    (47, 'Prima FC', 'prima-fc', true)
,
    (48, 'Majestic SC', 'majestic-sc', true)
,
    (49, 'Peachtree FC', 'peachtree-fc', true)
,
    (50, 'Bel Calcio FC', 'bel-calcio-fc', true)
,
    (51, 'Buckhead SC', 'buckhead-sc', true)
,
    (52, 'Alliance SC', 'alliance-sc', true)
,
    (53, 'SC Gwinnett', 'sc-gwinnett', true)
,
    (54, 'Georgia United FC', 'georgia-united-fc', true)

ON CONFLICT (id) DO NOTHING;

-- CASA clubs
INSERT INTO clubs (id, display_name, slug, is_active) VALUES
(1000, 'Ade United', 'ade-united', true),
(1001, 'Oaklyn II', 'oaklyn-ii', true),
(1002, 'Sierra Stars', 'sierra-stars', true),
(1003, 'Lighthouse Boys Club', 'lighthouse-boys-club', true),
(1004, 'Illyrians FC', 'illyrians-fc', true),
(1005, 'Black Stars', 'black-stars', true),
(1006, 'Phoenix I', 'phoenix-i', true),
(1007, 'PSC II', 'psc-ii', true),
(1008, 'Persepolis I', 'persepolis-i', true),
(1009, 'CF Armada', 'cf-armada', true),
(1010, 'Lighthouse Old Timers Club', 'lighthouse-old-timers-club', true),
(1011, 'Persepolis II', 'persepolis-ii', true),
(1012, 'Phoenix II', 'phoenix-ii', true),
(1013, 'Alloy Soccer Club Reserves', 'alloy-soccer-club-reserves', true),
(1014, 'F\x26M FC', 'f-x26m-fc', true),
(1015, 'Keystone Elite', 'keystone-elite', true),
(1016, 'Kutztown', 'kutztown', true),
(1017, 'Lancaster City FC', 'lancaster-city-fc', true),
(1018, 'BCFC All-Stars', 'bcfc-all-stars', true),
(1019, 'Flatley FC', 'flatley-fc', true),
(1020, 'Gambeta FC', 'gambeta-fc', true),
(1021, 'Jaguars United', 'jaguars-united', true),
(1022, 'South Shore FC', 'south-shore-fc', true),
(1023, 'Strictly Nos', 'strictly-nos', true),
(1024, 'Alaso FC', 'alaso-fc', true),
(1025, 'FeelsGood FC', 'feelsgood-fc', true),
(1026, 'Jersey Shore Boca', 'jersey-shore-boca', true),
(1027, 'Jersey Shore Hounds', 'jersey-shore-hounds', true),
(1028, 'MFC Stars', 'mfc-stars', true),
(1029, 'Milan Football Club', 'milan-football-club', true),
(1030, 'Monmouth Light FC', 'monmouth-light-fc', true),
(1031, 'Princeton International FC', 'princeton-international-fc', true),
(1032, 'Real Central NJ II', 'real-central-nj-ii', true),
(1033, 'Rondo Football Club', 'rondo-football-club', true);
