-- Sport Divisions (Football Home club divisions + scraped teams)
-- Each club has sport divisions (groups of teams by age/competition level)
-- By default: 1 club → 1 sport_division → 1+ teams
-- This file is generated by scrapers and committed to git

INSERT INTO sport_divisions (id, club_id, display_name, sport, is_active) VALUES
    (1, 1, 'Lighthouse Soccer', 'Soccer', true)
,
    (2, 2, 'Soccer', 'Soccer', true)
,
    (3, 3, 'Soccer', 'Soccer', true)
,
    (4, 4, 'Soccer', 'Soccer', true)
,
    (5, 5, 'Soccer', 'Soccer', true)
,
    (6, 6, 'Soccer', 'Soccer', true)
,
    (7, 7, 'Soccer', 'Soccer', true)
,
    (8, 8, 'Soccer', 'Soccer', true)
,
    (9, 9, 'Soccer', 'Soccer', true)
,
    (10, 10, 'Soccer', 'Soccer', true)
,
    (11, 11, 'Soccer', 'Soccer', true)
,
    (12, 12, 'Soccer', 'Soccer', true)
,
    (13, 13, 'Soccer', 'Soccer', true)
,
    (14, 14, 'Soccer', 'Soccer', true)
,
    (15, 15, 'Soccer', 'Soccer', true)
,
    (16, 16, 'Soccer', 'Soccer', true)
,
    (17, 17, 'Soccer', 'Soccer', true)
,
    (18, 18, 'Soccer', 'Soccer', true)
,
    (19, 19, 'Soccer', 'Soccer', true)
,
    (20, 20, 'Soccer', 'Soccer', true)
,
    (21, 21, 'Soccer', 'Soccer', true)
,
    (22, 22, 'Soccer', 'Soccer', true)
,
    (23, 23, 'Soccer', 'Soccer', true)
,
    (24, 24, 'Soccer', 'Soccer', true)
,
    (25, 25, 'Soccer', 'Soccer', true)
,
    (26, 26, 'Soccer', 'Soccer', true)
,
    (27, 27, 'Soccer', 'Soccer', true)
,
    (28, 28, 'Soccer', 'Soccer', true)
,
    (29, 29, 'Soccer', 'Soccer', true)
,
    (30, 30, 'Soccer', 'Soccer', true)
,
    (31, 31, 'Soccer', 'Soccer', true)
,
    (32, 32, 'Soccer', 'Soccer', true)
,
    (33, 33, 'Soccer', 'Soccer', true)
,
    (34, 34, 'Soccer', 'Soccer', true)
,
    (35, 35, 'Soccer', 'Soccer', true)
,
    (36, 36, 'Soccer', 'Soccer', true)
,
    (37, 37, 'Soccer', 'Soccer', true)
,
    (38, 38, 'Soccer', 'Soccer', true)
,
    (39, 39, 'Soccer', 'Soccer', true)
,
    (40, 40, 'Soccer', 'Soccer', true)
,
    (41, 41, 'Soccer', 'Soccer', true)
,
    (42, 42, 'Soccer', 'Soccer', true)
,
    (43, 43, 'Soccer', 'Soccer', true)
,
    (44, 44, 'Soccer', 'Soccer', true)
,
    (45, 45, 'Soccer', 'Soccer', true)
,
    (46, 46, 'Soccer', 'Soccer', true)
,
    (47, 47, 'Soccer', 'Soccer', true)
,
    (48, 48, 'Soccer', 'Soccer', true)
,
    (49, 49, 'Soccer', 'Soccer', true)
,
    (50, 50, 'Soccer', 'Soccer', true)
,
    (51, 51, 'Soccer', 'Soccer', true)
,
    (52, 52, 'Soccer', 'Soccer', true)
,
    (53, 53, 'Soccer', 'Soccer', true)

ON CONFLICT (id) DO NOTHING;
