-- Sport Divisions (Football Home club divisions + scraped teams)
-- Each club has sport divisions (groups of teams by age/competition level)
-- By default: 1 club → 1 sport_division → 1+ teams
-- This file is generated by scrapers and committed to git

INSERT INTO sport_divisions (id, club_id, display_name, sport_id, is_active) VALUES
    (1, 1, 'Lighthouse Soccer', 1, true)
,
    (2, 2, 'Falcons FC', 1, true)
,
    (3, 3, 'Scrub Nation', 1, true)
,
    (4, 4, 'Praia Kapital', 1, true)
,
    (5, 5, 'South Coast Union', 1, true)
,
    (6, 6, 'Project Football', 1, true)
,
    (7, 7, 'Invictus FC', 1, true)
,
    (8, 8, 'Fitchburg FC', 1, true)
,
    (9, 9, 'Somerville United FC', 1, true)
,
    (10, 10, 'KO Elites', 1, true)
,
    (11, 11, 'Glastonbury Celtic', 1, true)
,
    (12, 12, 'Wildcat FC', 1, true)
,
    (13, 13, 'Hermandad Connecticut', 1, true)
,
    (14, 14, 'NY Greek Americans', 1, true)
,
    (15, 15, 'Hoboken FC 1912', 1, true)
,
    (16, 16, 'NY Pancyprian Freedoms', 1, true)
,
    (17, 17, 'Lansdowne Yonkers FC', 1, true)
,
    (18, 18, 'Doxa FCW', 1, true)
,
    (19, 19, 'Leros SC', 1, true)
,
    (20, 20, 'NY International FC', 1, true)
,
    (21, 21, 'Richmond County FC', 1, true)
,
    (22, 22, 'Zum Schneider FC 03', 1, true)
,
    (23, 23, 'Central Park Rangers FC', 1, true)
,
    (24, 24, 'SC Vistula Garfield', 1, true)
,
    (25, 25, 'NY Athletic Club', 1, true)
,
    (26, 26, 'WC Predators', 1, true)
,
    (27, 27, 'Alloy Soccer Club', 1, true)
,
    (28, 28, 'Oaklyn United FC', 1, true)
,
    (29, 29, 'Real Central NJ Soccer', 1, true)
,
    (30, 30, 'Philadelphia Heritage SC', 1, true)
,
    (31, 31, 'Philadelphia Soccer Club', 1, true)
,
    (32, 32, 'Vidas United FC', 1, true)
,
    (33, 33, 'GAK', 1, true)
,
    (34, 34, 'Lighthouse 1893 SC', 1, true)
,
    (35, 35, 'Jersey Shore Boca', 1, true)
,
    (36, 36, 'Sewell Old Boys FC', 1, true)
,
    (37, 37, 'Medford Strikers', 1, true)
,
    (38, 38, 'Nova FC', 1, true)
,
    (39, 39, 'VA Marauders FC', 1, true)
,
    (40, 40, 'Wave FC', 1, true)
,
    (41, 41, 'PFA EPSL', 1, true)
,
    (42, 42, 'Grove Soccer United', 1, true)
,
    (43, 43, 'Christos FC', 1, true)
,
    (44, 44, 'Delmarva Thunder', 1, true)
,
    (45, 45, 'PW Nova', 1, true)
,
    (46, 46, 'Terminus FC', 1, true)
,
    (47, 47, 'Prima FC', 1, true)
,
    (48, 48, 'Majestic SC', 1, true)
,
    (49, 49, 'Peachtree FC', 1, true)
,
    (50, 50, 'Bel Calcio FC', 1, true)
,
    (51, 51, 'Buckhead SC', 1, true)
,
    (52, 52, 'Alliance SC', 1, true)
,
    (53, 53, 'SC Gwinnett', 1, true)
,
    (54, 54, 'Georgia United FC', 1, true)

ON CONFLICT (id) DO NOTHING;

-- CASA sport_divisions
INSERT INTO sport_divisions (id, club_id, sport_id, display_name, is_active) VALUES
(1000, 1000, 1, 'Ade United', true),
(1001, 1001, 1, 'Oaklyn II', true),
(1002, 1002, 1, 'Sierra Stars', true),
(1003, 1003, 1, 'Lighthouse Boys Club', true),
(1004, 1004, 1, 'Illyrians FC', true),
(1005, 1005, 1, 'Black Stars', true),
(1006, 1006, 1, 'Phoenix I', true),
(1007, 1007, 1, 'PSC II', true),
(1008, 1008, 1, 'Persepolis I', true),
(1009, 1009, 1, 'CF Armada', true),
(1010, 1010, 1, 'Lighthouse Old Timers Club', true),
(1011, 1011, 1, 'Persepolis II', true),
(1012, 1012, 1, 'Phoenix II', true),
(1013, 1013, 1, 'BCFC All-Stars', true),
(1014, 1014, 1, 'Flatley FC', true),
(1015, 1015, 1, 'Gambeta FC', true),
(1016, 1016, 1, 'Jaguars United', true),
(1017, 1017, 1, 'South Shore FC', true),
(1018, 1018, 1, 'Strictly Nos', true),
(1019, 1019, 1, 'Alaso FC', true),
(1020, 1020, 1, 'FeelsGood FC', true),
(1021, 1021, 1, 'Jersey Shore Boca', true),
(1022, 1022, 1, 'Jersey Shore Hounds', true),
(1023, 1023, 1, 'MFC Stars', true),
(1024, 1024, 1, 'Milan Football Club', true),
(1025, 1025, 1, 'Monmouth Light FC', true),
(1026, 1026, 1, 'Princeton International FC', true),
(1027, 1027, 1, 'Real Central NJ II', true),
(1028, 1028, 1, 'Rondo Football Club', true);
