-- Sport Divisions (scraped data)
-- Generated by ApslScraper + CasaScraper
-- Combined APSL + CASA sport divisions in single file
-- Differentiated by club_id → organizations → source_system_id

-- This file is generated by scrapers and committed to git for reproducibility
-- To regenerate: ./dev.sh --refresh
