-- Clubs (sport-specific competitive units owned by organizations)
-- Example: Lighthouse 1893 organization owns multiple clubs for different purposes:
-- - Lighthouse 1893 SC (competitive adult soccer)
-- - Lighthouse Boys Club (youth development)
-- - Lighthouse Old Timers (recreational 40+)
-- This file is generated by scrapers and committed to git

-- Manual clubs (not scraped)
-- Lighthouse 1893 organization owns these clubs
INSERT INTO clubs (id, organization_id, name, sport_id, is_active) VALUES
    (1, 1, 'Lighthouse 1893 SC', 1, true),
    (2, 1, 'Lighthouse Boys Club', 1, true),
    (3, 1, 'Lighthouse Old Timers', 1, true)
ON CONFLICT (id) DO NOTHING;

-- Placeholder - additional clubs will be populated by scrapers
