-- Teams (persistent entities)
-- Generated by ApslScraper + CasaScraper
-- Teams belong to clubs, register in divisions via division_rosters table

-- This file is generated by scrapers and committed to git
-- To regenerate: ./dev.sh --refresh

-- Manual teams (not scraped)
-- Each club can have multiple teams (e.g., A team, B team, U19, etc.)
INSERT INTO teams (id, club_id, name, city) VALUES
    (1, 1, 'Lighthouse 1893 SC', 'Mountain View'),
    (2, 2, 'Lighthouse Boys Club', 'Mountain View'),
    (3, 3, 'Lighthouse Old Timers', 'Mountain View')
ON CONFLICT (id) DO NOTHING;

-- Placeholder - additional teams will be populated by scrapers
-- Format: INSERT INTO teams (id, club_id, name) VALUES ...
