-- Division Rosters (team registrations in divisions)
-- Generated by scrapers - links teams to divisions (seasonal participation)
-- Renamed from team_divisions - league manages this relationship

-- This file is generated by scrapers and committed to git
-- To regenerate: ./dev.sh --refresh

-- Placeholder - will be populated by scrapers
-- Format: INSERT INTO division_rosters (id, division_id, team_id) VALUES ...
