-- Division Roster Players (rosters scoped to division registrations)
-- Generated by scrapers
-- Renamed from team_division_players

-- This file is generated by scrapers and committed to git
-- To regenerate: ./dev.sh --refresh

-- Placeholder - will be populated by scrapers
-- Format: INSERT INTO division_roster_players (division_roster_id, player_id, jersey_number) VALUES ...
