-- Match Divisions (scraped data)
-- Junction table linking matches to divisions
-- Generated by ApslScraper (APSL-specific, CASA doesn't use this)

-- This file is generated by scrapers and committed to git for reproducibility
-- To regenerate: ./dev.sh --refresh
