-- Match Divisions (Links matches to divisions)
-- Generated by database-driven scraper

INSERT INTO match_divisions (match_id, division_id)
SELECT DISTINCT
  m.id,
  td.division_id
FROM matches m
JOIN team_divisions td ON td.team_id = m.home_team_id
WHERE m.source_system_id = 1 -- APSL only
ON CONFLICT (match_id, division_id) DO NOTHING;
