-- Match Events (scraped data)
-- Goals, cards, substitutions, etc.
-- Generated by ApslScraper + CasaScraper
-- Combined APSL + CASA match events in single file

-- This file is generated by scrapers and committed to git for reproducibility
-- To regenerate: ./dev.sh --refresh
