-- Match Lineups (scraped data)
-- Player appearances in matches
-- Generated by ApslScraper + CasaScraper
-- Combined APSL + CASA match lineups in single file

-- This file is generated by scrapers and committed to git for reproducibility
-- To regenerate: ./dev.sh --refresh
