-- ========================================
-- CASA TEAM COACHES
-- ========================================
-- Scraped from CASA roster data
-- Generated by CasaScraper.js
-- ========================================

-- This file will be auto-generated by the scraper
-- Links coaches to teams with their role

