-- Tactical Boards - Development App Data
-- Auto-generated by SqlFileLogger when tactical boards are created/modified in the app
-- Format: ##u-{table}-app.sql (u = development/testing environment)

