-- ============================================================================
-- 045-cross-league-curation.sql
-- AUTO-GENERATED: 2026-01-30T22:08:49.107Z
-- ============================================================================
--
-- Purpose: Merge related teams under parent clubs across all leagues
-- Generated by: database/scripts/generate-curation.js
--
-- REVIEW CAREFULLY before committing!
-- Edit/delete any merges that don't look right.
--

-- ============================================================================
-- Alloy Soccer Club
-- ============================================================================

-- Using existing parent club: Alloy Soccer Club (club_id: 27)
DO $$
DECLARE
    parent_club_id INTEGER := 27;
BEGIN

    -- Skip: Alloy Soccer Club (apsl) - already has parent club
    -- Skip: Alloy Soccer Club Reserves (casa) - already has parent club
END $$;

-- ============================================================================
-- Barnstonworth Rovers FC
-- ============================================================================

-- Using existing parent club: Barnstonworth Rovers FC (club_id: 123)
DO $$
DECLARE
    parent_club_id INTEGER := 123;
BEGIN

    -- Merge: Barnstonworth Rovers FC (csl)
    UPDATE teams SET club_id = parent_club_id WHERE id = 165;

    -- Merge: Barnstonworth Rovers FC Old Boys (csl)
    UPDATE teams SET club_id = parent_club_id WHERE id = 186;

    -- Merge: Barnstonworth Rovers Old Boys (csl)
    UPDATE teams SET club_id = parent_club_id WHERE id = 232;

    -- Clean up orphan clubs
    DELETE FROM clubs WHERE id IN (203);

END $$;

-- ============================================================================
-- Block FC
-- ============================================================================

-- Using existing parent club: Block FC (club_id: 126)
DO $$
DECLARE
    parent_club_id INTEGER := 126;
BEGIN

    -- Merge: Block FC (csl)
    UPDATE teams SET club_id = parent_club_id WHERE id = 101;

    -- Merge: Block FC II (csl)
    UPDATE teams SET club_id = parent_club_id WHERE id = 109;

    -- Clean up orphan clubs
    DELETE FROM clubs WHERE id IN (204);

END $$;

-- ============================================================================
-- Borgetto FC
-- ============================================================================

-- Using existing parent club: Borgetto FC (club_id: 129)
DO $$
DECLARE
    parent_club_id INTEGER := 129;
BEGIN

    -- Merge: Borgetto FC (csl)
    UPDATE teams SET club_id = parent_club_id WHERE id = 188;

    -- Merge: Borgetto FC II (csl)
    UPDATE teams SET club_id = parent_club_id WHERE id = 192;

    -- Clean up orphan clubs
    DELETE FROM clubs WHERE id IN (205);

END $$;

-- ============================================================================
-- Brooklyn City FC
-- ============================================================================

-- Using existing parent club: Brooklyn City FC (club_id: 132)
DO $$
DECLARE
    parent_club_id INTEGER := 132;
BEGIN

    -- Merge: Brooklyn City FC (csl)
    UPDATE teams SET club_id = parent_club_id WHERE id = 120;

    -- Merge: Brooklyn City FC II (csl)
    UPDATE teams SET club_id = parent_club_id WHERE id = 140;

    -- Merge: Brooklyn City FC III (csl)
    UPDATE teams SET club_id = parent_club_id WHERE id = 161;

    -- Clean up orphan clubs
    DELETE FROM clubs WHERE id IN (200);

END $$;

-- ============================================================================
-- CD Iberia
-- ============================================================================

-- Using existing parent club: CD Iberia (club_id: 137)
DO $$
DECLARE
    parent_club_id INTEGER := 137;
BEGIN

    -- Merge: CD Iberia (csl)
    UPDATE teams SET club_id = parent_club_id WHERE id = 202;

    -- Merge: CD Iberia II (csl)
    UPDATE teams SET club_id = parent_club_id WHERE id = 208;

    -- Clean up orphan clubs
    DELETE FROM clubs WHERE id IN (206);

END $$;

-- ============================================================================
-- Central Park Rangers FC
-- ============================================================================

-- Using existing parent club: Central Park Rangers FC (club_id: 22)
DO $$
DECLARE
    parent_club_id INTEGER := 22;
BEGIN

    -- Skip: Central Park Rangers 1999 (csl) - already has parent club
    -- Skip: Central Park Rangers FC (apsl) - already has parent club
    -- Skip: Central Park Rangers FC 1999 (csl) - already has parent club
    -- Skip: Central Park Rangers Green (csl) - already has parent club
    -- Skip: Central Park Rangers II (csl) - already has parent club
    -- Skip: Central Park Rangers III (csl) - already has parent club
    -- Skip: Central Park Rangers Kickoff (csl) - already has parent club
    -- Skip: Central Park Rangers Kickoff II (csl) - already has parent club
    -- Skip: Central Park Rangers Legends (csl) - already has parent club
    -- Skip: Central Park Rangers Lower East (csl) - already has parent club
    -- Skip: Central Park Rangers Lower East II (csl) - already has parent club
    -- Skip: Central Park Rangers Old Boys (csl) - already has parent club
    -- Skip: Central Park Rangers Orange (csl) - already has parent club
    -- Skip: Central Park Rangers Red (csl) - already has parent club
    -- Skip: Central Park Rangers Red II (csl) - already has parent club
    -- Skip: Central Park Rangers United (csl) - already has parent club
    -- Skip: Central Park Rangers United II (csl) - already has parent club
    -- Skip: Central Park Rangers Young Boys (csl) - already has parent club
END $$;

-- ============================================================================
-- Lighthouse 1893 SC
-- ============================================================================

-- Using existing parent club: Lighthouse 1893 SC (club_id: 35)
DO $$
DECLARE
    parent_club_id INTEGER := 35;
BEGIN

    -- Skip: Lighthouse 1893 SC (apsl) - already has parent club
    -- Skip: Lighthouse Boys Club (casa) - already has parent club
    -- Skip: Lighthouse Old Timers Club (casa) - already has parent club
END $$;

-- ============================================================================
-- Manhattan Celtic
-- ============================================================================

-- Using existing parent club: Manhattan Celtic (club_id: 66)
DO $$
DECLARE
    parent_club_id INTEGER := 66;
BEGIN

    -- Skip: Manhattan Celtic (csl) - already has parent club
    -- Skip: Manhattan Celtic Bhoys (csl) - already has parent club
    -- Skip: Manhattan Celtic II (csl) - already has parent club
    -- Skip: Manhattan Celtic III (csl) - already has parent club
    -- Skip: Manhattan Celtic Masters (csl) - already has parent club
END $$;

-- ============================================================================
-- Manhattan FC
-- ============================================================================

-- Using existing parent club: Manhattan FC (club_id: 199)
DO $$
DECLARE
    parent_club_id INTEGER := 199;
BEGIN

    -- Merge: Manhattan FC (csl)
    UPDATE teams SET club_id = parent_club_id WHERE id = 198;

    -- Merge: Manhattan FC II (csl)
    UPDATE teams SET club_id = parent_club_id WHERE id = 209;

    -- Merge: Manhattan FC III (csl)
    UPDATE teams SET club_id = parent_club_id WHERE id = 261;

    -- Clean up orphan clubs
    DELETE FROM clubs WHERE id IN (201);

END $$;

-- ============================================================================
-- Manhattan Kickers
-- ============================================================================

-- Using existing parent club: Manhattan Kickers (club_id: 202)
DO $$
DECLARE
    parent_club_id INTEGER := 202;
BEGIN

    -- Skip: Manhattan Kickers (csl) - already has parent club
    -- Skip: Manhattan Kickers II (csl) - already has parent club
    -- Skip: Manhattan Kickers Legends (csl) - already has parent club
END $$;

-- ============================================================================
-- UNMATCHED TEAMS (need manual review)
-- ============================================================================
--
-- The following teams didn't match any curation rules.
-- Review and add rules to generate-curation.js if needed.
--
-- AC Trilogy (apsl)
-- Adé United FC (casa)
-- Afghan Ittihad FC (csl)
-- Al-Asad (csl)
-- Albion SC Delaware (apsl)
-- Alliance SC (apsl)
-- Astoria Knights II (csl)
-- Aurora FC (csl)
-- BALL WORLD (apsl)
-- BCFC All Stars (casa)
-- Bajas FC (csl)
-- Baltimore City FC (apsl)
-- Bel Calcio FC (apsl)
-- Bobcats FC U23 (apsl)
-- Bolivia Si Existe FC (csl)
-- Boston City FC (apsl)
-- Boston Ethiopians (apsl)
-- Braza Futbol (csl)
-- Brooklyn New York SC (csl)
-- Buckhead SC (apsl)
-- C.A. Islas Malvinas (csl)
-- Caribbean FCA (csl)
-- Christos FC (apsl)
-- Clarkstown SC (csl)
-- Club Internacional (csl)
-- Club de Futbol Armada (casa)
-- Columbia FC (apsl)
-- Cozmoz FC (csl)
-- Delmarva Thunder (apsl)
-- Desportiva Sociedad (csl)
-- Desportiva Sociedad City (csl)
-- Desportiva Sociedad Fury (csl)
-- Desportiva Sociedad II (csl)
-- Desportiva Sociedad NY (csl)
-- Desportiva Sociedad NY II (csl)
-- Doxa FCW (apsl)
-- Doxa SC (apsl)
-- Doxa SC Legends (csl)
-- Dulles N-Lite FC (apsl)
-- ERFC (csl)
-- ERFC Hudson (csl)
-- ERFC II (csl)
-- Estudiantes FC (apsl)
-- F&M FC (casa)
-- FC Japan (csl)
-- FC Japan II (csl)
-- FC Neman Philadelphia (apsl)
-- FC Partizani NY (csl)
-- FC Sandzak (csl)
-- FC Sandzak II (csl)
-- FC Ulqini (csl)
-- FC Ulqini II (csl)
-- Falco FC (csl)
-- Falco FC II (csl)
-- Falcons FC (apsl)
-- Fall River FC (apsl)
-- Fall River Marksmen (apsl)
-- FanDuel FC (csl)
-- Fitchburg FC (apsl)
-- Flatley FC (casa)
-- Flatley FC (apsl)
-- Florence F.C. (apsl)
-- GAK (apsl)
-- Gambeta FC (casa)
-- Georgia United FC (apsl)
-- Germantown City FC (apsl)
-- Glastonbury Celtic (apsl)
-- Glenmont FC (apsl)
-- Golden Ball Soccer Academy (apsl)
-- Grove Soccer United (apsl)
-- Guanabara SC (apsl)
-- Guyana Sunnydale Veterans FC (csl)
-- Hermandad Connecticut (apsl)
-- Hoboken FC 1912 (apsl)
-- Hoboken FC 1912 II (csl)
-- Hoboken FC 1912 III (csl)
-- Illyrians FC (casa)
-- Inter Vidas (apsl)
-- Invictus FC (apsl)
-- Jaguars United FC (apsl)
-- Jaguars United FC (casa)
-- Jersey Shore Boca (apsl)
-- Jessup Football Club (apsl)
-- Junior Mafia FC (csl)
-- KO Elites (apsl)
-- Kaizen FC (csl)
-- Kaizen FC II (csl)
-- Kelmendi FC NY (csl)
-- Kelmendi FC NY II (csl)
-- Kensington SC (apsl)
-- Kickoff FC (csl)
-- Kickoff FC II (csl)
-- KidSuper Samba AC (apsl)
-- KidSuper Samba AC II (csl)
-- KidSuper Samba AC III (csl)
-- Koru Soccer Academy (csl)
-- Laberia FC (csl)
-- Laberia FC II (csl)
-- Lancaster City FC (casa)
-- Lansdowne Yonkers FC (apsl)
-- Lansdowne Yonkers FC Metro (csl)
-- Leros SC (apsl)
-- Majestic SC (apsl)
-- Mass United Rush (apsl)
-- Medford Strikers (apsl)
-- Missile FC (csl)
-- Missile FC II (csl)
-- NY Albanians FC (csl)
-- NY Athletic Club (csl)
-- NY Athletic Club II (csl)
-- NY Croatia (csl)
-- NY Eagles FC (csl)
-- NY Eagles SC (csl)
-- NY Finest FC (csl)
-- NY Finest FC II (csl)
-- NY Galicia (csl)
-- NY Galicia II (csl)
-- NY Greek Americans (apsl)
-- NY International FC (csl)
-- NY International FC II (csl)
-- NY International FC III (csl)
-- NY Irish SC Legends (csl)
-- NY Legacy FC (csl)
-- NY Pancyprian Freedoms (apsl)
-- NY Pancyprian Freedoms II (csl)
-- NY Shamrocks (csl)
-- NY Shamrocks II (csl)
-- NY Shamrocks Legends (csl)
-- NY Titans FC (csl)
-- NY Ukrainians (csl)
-- NY Ukrainians II (csl)
-- NYC AlphaStars Club (csl)
-- NYPD FC (csl)
-- NYPD FC II (csl)
-- NYPD FC Veterans (csl)
-- Nova FC (apsl)
-- Nova FC O30 (apsl)
-- Nova FC WL (apsl)
-- Oaklyn United FC (apsl)
-- Oaklyn United FC II (casa)
-- Ollama FC (csl)
-- PFA EPSL (apsl)
-- PW Nova (apsl)
-- Panatha USA (csl)
-- Peachtree FC (apsl)
-- Pelham Parkway FC (csl)
-- Persepolis FC (casa)
-- Persepolis United FC II (casa)
-- Philadelphia Heritage SC (apsl)
-- Philadelphia SC II (casa)
-- Philadelphia Soccer Club (apsl)
-- Phoenix SCM (casa)
-- Phoenix SCR (casa)
-- Polonez SC (csl)
-- Polonia SC (csl)
-- Polonia SC II (csl)
-- Praia Kapital (apsl)
-- Prima FC (apsl)
-- Project Football (apsl)
-- Queens Tigers FC (csl)
-- Real Central NJ Soccer (apsl)
-- Richmond County FC (csl)
-- Richmond County FC II (csl)
-- Ridgewood Romac SC (csl)
-- Riverside Squires (csl)
-- Ruggles Pro FC (apsl)
-- SC Eintracht (csl)
-- SC Eintracht II (csl)
-- SC Eintracht Legends (csl)
-- SC Football Crew (csl)
-- SC Gjoa (csl)
-- SC Gjoa Over-40 (csl)
-- SC Gjoa Yellow Hook (csl)
-- SC Gjoa Yellow Hook II (csl)
-- SC Gwinnett (apsl)
-- SC Vistula Garfield (apsl)
-- Salisbury Steaks (apsl)
-- Salone FC (apsl)
-- Santa Cruz FC EPSL (apsl)
-- Scots-American AC (apsl)
-- Scrub Nation (apsl)
-- Seft F.C. (apsl)
-- Sete Setembro USA (apsl)
-- Sewell Old Boys FC (apsl)
-- SmartSports FC (csl)
-- Soccer Legion FC Men (csl)
-- Somerville United FC (apsl)
-- Soricha Foot SC (csl)
-- Soricha Foot SC II (csl)
-- South Bronx United (csl)
-- South Bronx United II (csl)
-- South Coast Union (apsl)
-- South Shore FC (casa)
-- Sporting Astoria Dawgz (csl)
-- Sporting Astoria SBU Dawgz (csl)
-- Sporting Astoria SBU OG'S (csl)
-- Sporting Astoria SC (csl)
-- Sporting Astoria SC II (csl)
-- Sporting Astoria SC OG'S (csl)
-- Sporting Astoria South Bronx United (csl)
-- Sporting Astoria South Bronx United II (csl)
-- Stal Mielec NY (csl)
-- Stal Mielec NY II (csl)
-- Strictly Nos FC (apsl)
-- Strictly Nos Fc (casa)
-- Suffolk County FC (apsl)
-- Terminus FC (apsl)
-- Tibet FC (csl)
-- Trem Bala FC USA (apsl)
-- Tres Barras (apsl)
-- Unknown FC (apsl)
-- VA Marauders FC (apsl)
-- VA Marauders FC WL (apsl)
-- Vera FC (csl)
-- Vibes FC (csl)
-- Vibes FC II (csl)
-- Vidas Elite (apsl)
-- Vidas United FC (apsl)
-- Villanovence F.C. (apsl)
-- Villanovence FC (apsl)
-- Vllaznia NYC (csl)
-- Vllaznia NYC II (csl)
-- WC Predators (apsl)
-- Warriors NYC (csl)
-- Wave FC (apsl)
-- Whitestone FC (csl)
-- Wildcat FC (apsl)
-- Williamsburg International FC (csl)
-- Williamsburg International FC II (csl)
-- Williamsburg International FC III (csl)
-- Yemen United SC (csl)
-- Yemen United SC II (csl)
-- Zum Schneider FC 03 (apsl)
-- Zum Schneider FC 03 II (csl)
-- Zum Schneider FC 03 III (csl)
