-- ========================================
-- APSL LEAGUE DATA (AUTO-GENERATED)
-- ========================================
-- Generated: 2025-12-07T00:03:16.142Z
-- Source: https://apslsoccer.com/standings/
-- Includes: Conferences, Divisions, Teams, Players
--
-- This file is automatically regenerated on rebuild.
-- Uses ON CONFLICT DO UPDATE for idempotent inserts.
-- ========================================

