#!/bin/bash
# Post-scrape conversion for APSL scraper
# Converts generated INSERT SQL files to COPY format for fast loading

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONVERT_SCRIPT="$SCRIPT_DIR/../convert-to-copy.sh"
DATA_DIR="$SCRIPT_DIR/../../data"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

echo ""
echo -e "${BLUE}Converting APSL SQL files to COPY format...${NC}"
echo ""

# Files generated by APSL scraper
FILES=(
    "$DATA_DIR/08b-users-apsl.sql"
    "$DATA_DIR/13b-players-apsl.sql"
    "$DATA_DIR/14-rosters.sql"
)

# Convert each file
"$CONVERT_SCRIPT" "${FILES[@]}"

echo -e "${GREEN}✓ APSL COPY conversion complete${NC}"
echo ""
