#!/bin/bash
# Post-scrape conversion for venue scraper
# Converts generated INSERT SQL files to COPY format for fast loading

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONVERT_SCRIPT="$SCRIPT_DIR/../convert-to-copy.sh"
DATA_DIR="$SCRIPT_DIR/../../data"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

echo ""
echo -e "${BLUE}Converting venue SQL files to COPY format...${NC}"
echo ""

# Files generated by venue scraper
"$CONVERT_SCRIPT" "$DATA_DIR/02-venues.sql"

echo -e "${GREEN}✓ Venue COPY conversion complete${NC}"
echo ""
