-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
-- Clubs - CASA
-- Total Records: 28
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

INSERT INTO clubs (id, name, organization_id) SELECT 20000, 'Adé United FC', (SELECT id FROM organizations WHERE name = 'Adé United FC') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Adé United FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20001, 'Oaklyn United FC', (SELECT id FROM organizations WHERE name = 'Oaklyn United FC') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Oaklyn United FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20002, 'Philadelphia Sierra Stars', (SELECT id FROM organizations WHERE name = 'Philadelphia Sierra Stars') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Philadelphia Sierra Stars') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20003, 'Persepolis FC', (SELECT id FROM organizations WHERE name = 'Persepolis FC') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Persepolis FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20004, 'Philly BlackStars', (SELECT id FROM organizations WHERE name = 'Philly BlackStars') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Philly BlackStars') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20005, 'Phoenix SCM', (SELECT id FROM organizations WHERE name = 'Phoenix SCM') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Phoenix SCM') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20006, 'Illyrians FC', (SELECT id FROM organizations WHERE name = 'Illyrians FC') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Illyrians FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20007, 'Lighthouse', (SELECT id FROM organizations WHERE name = 'Lighthouse') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Lighthouse') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20008, 'Philadelphia SC Select', (SELECT id FROM organizations WHERE name = 'Philadelphia SC Select') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Philadelphia SC Select') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20009, 'Sewell''s', (SELECT id FROM organizations WHERE name = 'Sewell''s') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Sewell''s') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20010, 'Lighthouse Boys Club U23', (SELECT id FROM organizations WHERE name = 'Lighthouse Boys Club U23') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Lighthouse Boys Club U23') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20011, 'Club de Futbol Armada', (SELECT id FROM organizations WHERE name = 'Club de Futbol Armada') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Club de Futbol Armada') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20012, 'South Shore FC', (SELECT id FROM organizations WHERE name = 'South Shore FC') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'South Shore FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20013, 'Jaguars United FC', (SELECT id FROM organizations WHERE name = 'Jaguars United FC') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Jaguars United FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20014, 'Strictly Nos Fc', (SELECT id FROM organizations WHERE name = 'Strictly Nos Fc') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Strictly Nos Fc') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20015, 'BCFC All Stars', (SELECT id FROM organizations WHERE name = 'BCFC All Stars') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'BCFC All Stars') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20016, 'Flatley FC', (SELECT id FROM organizations WHERE name = 'Flatley FC') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Flatley FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20017, 'Gambeta FC', (SELECT id FROM organizations WHERE name = 'Gambeta FC') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Gambeta FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20018, 'Somerville United FC', (SELECT id FROM organizations WHERE name = 'Somerville United FC') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Somerville United FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20019, 'Alloy Soccer Club', (SELECT id FROM organizations WHERE name = 'Alloy Soccer Club') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Alloy Soccer Club') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20020, 'Kutztown Men''s Soccer', (SELECT id FROM organizations WHERE name = 'Kutztown Men''s Soccer') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Kutztown Men''s Soccer') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20021, 'Lancaster City FC', (SELECT id FROM organizations WHERE name = 'Lancaster City FC') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Lancaster City FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20022, 'F&M FC', (SELECT id FROM organizations WHERE name = 'F&M FC') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'F&M FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20023, 'Keystone Elite', (SELECT id FROM organizations WHERE name = 'Keystone Elite') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Keystone Elite') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20024, 'Millersville Men''s Club Soccer', (SELECT id FROM organizations WHERE name = 'Millersville Men''s Club Soccer') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Millersville Men''s Club Soccer') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20025, 'Lancaster Bible College', (SELECT id FROM organizations WHERE name = 'Lancaster Bible College') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'Lancaster Bible College') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20026, 'West Chester University Club', (SELECT id FROM organizations WHERE name = 'West Chester University Club') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'West Chester University Club') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
INSERT INTO clubs (id, name, organization_id) SELECT 20027, 'YorkPA FC', (SELECT id FROM organizations WHERE name = 'YorkPA FC') WHERE NOT EXISTS (SELECT 1 FROM clubs WHERE name = 'YorkPA FC') ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, organization_id = EXCLUDED.organization_id;
